hotwired/turbo

- src/polyfills/submit-event.ts
Follow-up to https://github.com/hotwired/turbo/pull/1#discussion_r546728950
Replaces the `SubmitEvent` polyfill's `type` attribute access with
[`type property access][type].
[type]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement#Properties
> Modify SubmitEvent polyfill to read `type` property

- src/core/drive/form_submission.ts
- src/core/drive/navigator.ts
- src/core/frames/frame_controller.ts
- src/http/fetch_response.ts
- src/tests/fixtures/422.html
- src/tests/fixtures/500.html
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/server.ts
Related to https://github.com/hotwired/turbo-rails/issues/12
Related to https://github.com/hotwired/turbo-rails/issues/34
Typically, Turbo expects each FormSubmission request to result in a
redirect to a new Location.
When a FormSubmission request fails with an HTTP Status code between
400-499 or 500-599 (e.g. [unprocessable entity][422]), render the
response HTML. This commit brings the same behavior to `<turbo-frame>`
elements.
[422]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
> Render 400-500 status response HTML

- src/core/session.ts
- src/observers/form_submit_observer.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Similar to [Disabling Turbo Drive on Specific Links][turbo-drive-false],
guard intercepting form subissions with a similar check for
`[data-turbo-drive="false"]` on the submitter, `<form>` element, or an
ancestor.
Similarly, *do not intercept* when the submitter or form element
specifies a method that isn't an HTTP verb (via
[formmethod="dialog"][formmethod] attribute or [method="dialog"][method]
attribute, respectively).
In practice, HTTP submitting `<form>` elements will only ever declare
`method="get"` or `method="post"`. The one [exceptional case is
`method="dialog"`][method-dialog], which we check for as a special case.
Testing
---
Since we're covering behavior for the `<dialog>` element _and_ running
the suite in both Chrome and Firefox, the test suite needs to polyfill
support for …
> Enable opting-out of form submissions

- src/core/drive/form_submission.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/server.ts
Closes https://github.com/hotwired/turbo/issues/69
Reverts part of [bf257f3][] to read a [`<form>` element's `method`
attribute][attribute] _directly_, instead of through the corresponding
[HTMLFormElement.method][property].
Add test coverage for a `PUT` request to ensure that methods that are
not `GET` or `POST` are supported during `FetchRequest` serialization.
[bf257f3]: https://github.com/hotwired/turbo/commit/bf257f3c40e9566955ad8a7329060a9e276fd429
[attribute]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-method
[property]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/method
> Read form method as attribute instead of property

- src/core/frames/frame_controller.ts
- src/elements/frame_element.ts
- src/observers/appearance_observer.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/frames.html
- src/tests/fixtures/frames/frame.html
- src/tests/fixtures/loading.html
- src/tests/fixtures/navigation.html
- src/tests/functional/index.ts
- src/tests/functional/loading_tests.ts
Add support for declaring `[loading="lazy"]` (in the style of
[`iframe[loading="lazy"]`][iframe-loading] and
[`img[loading="lazy"]`][img-loading]). When both `src` and
`loading="lazy"` are declared on the frame, navigation will be deferred
until the element is visible in the document.
As an example, consider a `<details>`/`<summary>` pairing:
```html
<details>
<summary>Lazy load</summary>
<turbo-frame id="frame" src="/lazy-loaded.html" loading="lazy"></turbo-frame>
</details>
```
On initial load, the frame's contents will be empty. When the
`<summary>` element is clicked and the contents are visible, the
`<turbo-frame>` element will navigate to the URL specified in the `src`
element.
By default, `<turbo-frame>` elements that omit the `loading` attribute
will be treated as if they've …
> Support Lazy-loading `<turbo-frame>` contents

- src/http/fetch_response.ts
- src/observers/stream_observer.ts
- src/tests/server.ts
Using the `text/` prefix allows browsers' web inspectors to display the payload as text instead of displaying a message saying it's unpresentable.
Closes #24, #91
/cc @dhh
> Switch Turbo Streams to `text/vnd.turbo-stream.html`

- src/core/drive/visit.ts
- src/core/native/browser_adapter.ts
- src/core/snapshot.ts
- src/core/url.ts
- src/core/view.ts
- src/tests/functional/navigation_tests.ts
This is a port of https://github.com/turbolinks/turbolinks/pull/285 to resolve https://github.com/turbolinks/turbolinks/issues/75, https://github.com/turbolinks/turbolinks/issues/214, and https://github.com/turbolinks/turbolinks/issues/192
Clicking on a link which references an anchor on the current page issues an unnecessary request. This can cause problems when linking to content which is lazily loaded (see https://agile-reef-88023.herokuapp.com/posts/1), as well as with [analytics](https://github.com/turbolinks/turbolinks/issues/75#issuecomment-255867311) and [skip links](https://github.com/hotwired/turbo/issues/42). Disabling Turbo completely on those links prevents the request, but because the view is not cached, this approach breaks the Back button.
This PR detects whether the visit …
> Prevent reloading pages when tapping same-page anchors

- src/core/drive/form_submission.ts
- src/http/fetch_request.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/helpers/functional_test_case.ts
- src/tests/server.ts
Closes https://github.com/hotwired/turbo/issues/76
According to the HTML Specification for [Form Submission Encoding][],
there are three possible values:
* [application/x-www-form-urlencoded][] (the default value)
* [multipart/form-data][]
* [text/plain][]
[Encoding declarations on `<form method="get">` elements are
ignored][get-ignored].
This commit re-structures the `FetchRequest` constructor, and moves the
FormData to URL parameter encoding process _out_ to the `FormSubmission`
itself, since the `HTMLFormElement` knows about its [enctype][] and the
submitter its [formenctype][].
[Form Submission Encoding]: https://www.w3.org/TR/html52/sec-forms.html#selecting-a-form-submission-encoding
[application/x-www-form-urlencoded]: https://www.w3.org/TR/html52/sec-forms.html#selecting-a-form-subm …
> Form Encoding

- src/core/drive/navigator.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/greetings.ejs
- src/tests/functional/form_submission_tests.ts
- src/tests/server.ts
Closes https://github.com/hotwired/turbo/issues/126
When submitting a `<form method="get">`, skip the Form Submission
lifecycle and instead initiate a Visit.
Testing
---
Resolve an issue that caused false positives in our test suite when
monitoring whether or not an action triggered a form submission.
> Transform GET submissions into Visits

- src/core/drive/form_submission.ts
- src/core/streams/stream_message.ts
- src/observers/stream_observer.ts
Closes https://github.com/hotwired/turbo/issues/139
Since Turbo Stream responses over HTTP are in response to user
interactions, and the conventional way to trigger destructive user
interactions is through form submissions, this commit limits the
`StreamObserver` _only_ inject the [Accept][] header containing the
`text/html; turbo-stream` content type during form submissions.
Replace the [`turbo:before-fetch-request` event listener][turbo-event]
with a `turbo:submit-start` event listener.
From a Rails perspective, this enables an interesting pattern. Consider
the following controller:
```ruby
class MessagesController < ApplicationController
def create
@message = Message.new(params.require(:message).permit(:body))
if @message.save
redirect_to messages_url
else
render :new
end
end
end
``` …
> Restrict Accept: turbo-stream to Form Submissions

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/frames/frame.html
- src/tests/functional/frame_tests.ts
Closes https://github.com/hotwired/turbo/issues/115
When navigating via an `<a>` click within a `<turbo-frame>`, determine
the target of the navigation by checking for `[data-turbo-frame]`
overrides on the `<a>` element itself, and then check for frames
rreferenced by `turbo-frame[target]`, then fall back to the frame
itself.
> Read frame target from turbo-frame[target]

- src/core/drive/form_submission.ts
- src/core/frames/frame_controller.ts
- src/http/fetch_request.ts
- src/tests/fixtures/stream.html
- src/tests/functional/stream_tests.ts
- src/tests/server.ts
Closes https://github.com/hotwired/turbo/issues/141.
Follows-up https://github.com/hotwired/turbo/pull/52.
---
When creating the headers for a `FetchRequest`, provide the default
headers to the delegate by adding an argument to the
`additionalHeadersForRequest` signature so that delegates can
incorporate the current values if they choose to. They're passed as a
copy to prevent delegates from destructively acting upon them, with the
intention that delegates merge values _into_ them.
Testing
---
Add a guard middleware to the test server to reject _all_ requests that
don't specify an [Accept][] header containing `"text/html,
application/xhtml+xml"`.
Next, guard Stream requests with a similar check for
`"text/vnd.turbo-stream.html"`. Since those endpoints are behind the
guard middleware, …
> Restore correct Accept header for form submissions

- src/http/fetch_request.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/helpers/functional_test_case.ts
Closes https://github.com/hotwired/turbo/issues/107
The [HTML specification][] outlines the algorithm for handling form
submissions, and describes the steps involved in handling a `method=get`
request with `application/x-www-form-urlencoded` encoding.
However, it doesn't explicitly mention how to handle a `<form
method="get">` submission when the `action` attribute is omitted and the
current URL includes a query parameter that would be included within the
`<form>` element fields' values.
Determining the test cases to reproduce browser default behavior
involved was some trial and error troubleshooting in real browsers with
default (JavaScript-less) `<form>` submission handling.
The algorithm appears to be as follows:
* If there are no query parameters, append all field values as query …
> GET form submissions to the current path

- src/tests/fixtures/form.html
- src/tests/fixtures/navigation.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/navigation_tests.ts
Support for the `[disabled]` attribute pre-dates this commit, but is
largely untested. Prior to [hotwired/turbo-site#32][] and
[hotwired/turbo-site#36][], there were no mentions of the attribute in
the Turbo [Handbook][] or [Reference][] documentation.
This commit adds functional test-level coverage for the existing
behavior. When an `<a>` or `<form>` element targets a `<turbo-frame
disabled>` element, Turbo skips intercepting and intervening, and
instead navigates the page.
Testing
---
In addition, to avoid conflating `[data-turbo="false"]` and
`<turbo-frame disabled>`, this commit also renames test and test fixture
mentions of "disabled" to more accurately reflect which manner of
skipping behavior is being tested.
[Handbook]: https://github.com/hotwired/turbo-site/blob/52d5e7f1dfc26ac7a6 …
> Add test coverage for turbo-frame[disabled]

- src/core/drive/page_renderer.ts
- src/core/drive/visit.ts
- src/core/renderer.ts
- src/core/snapshot.ts
- src/tests/fixtures/autofocus.html
- src/tests/fixtures/frames.html
- src/tests/fixtures/frames/form.html
- src/tests/fixtures/frames/frame.html
- src/tests/fixtures/navigation.html
- src/tests/functional/autofocus_tests.ts
- src/tests/functional/frame_tests.ts
- src/tests/functional/index.ts
Focus [autofocus] on navigation and frame load
===
According to the `<input>` element's documentation for the
`[autofocus]` attribute:
> A Boolean attribute which, if present, indicates that the input should
> automatically have focus when the page has finished loading
>
>
> Note: An element with the `[autofocus]` attribute may gain focus
> before the `DOMContentLoaded` event is fired. No more than one element
> in the document may have the `[autofocus]` attribute. If put on more
> than one element, the **first one with the attribute receives focus**.
[autofocus]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#htmlattrdefautofocus
Focus the Snapshot that is connected to the DOM
===
During the rendering process, the `PageRenderer` replaces the current
`Snapshot` with the …
> Focus [autofocus] on navigation and frame load 

- src/core/drive/form_submission.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
When a `<form>` element's submitter declares a `[name]` attribute
without a `[value]` attribute, it is appended to the submission's
`FormData` instance twice. Due to a quirky difference between Safari and
Firefox + Chrome, the duplication _only_ occurs in Safari, which is a
browser that we are not running our functional test suite against.
In spite of that, this commit adds test coverage to ensure we don't
introduce a similar regression into those browsers.
Testing
---
Oddly enough, there are several occurrences of doubled-up `await await`
keywords, which this commit removes.
> Don't duplicate Form Submitter [name] param

- src/core/drive/navigator.ts
- src/core/frames/frame_controller.ts
When submitting a Form, Turbo Drive requires that the response redirects
to a `GET` via a [303 HTTP Status Code][303].
This requirement is enforced in
[FormSubmission.requestSucceededWithResponse][]:
```javascript
requestSucceededWithResponse(request: FetchRequest, response: FetchResponse) {
// ...
} else if (this.requestMustRedirect(request) && responseSucceededWithoutRedirect(response)) {
const error = new Error("Form responses must redirect to another location")
this.delegate.formSubmissionErrored(this, error)
} else {
// ...
}
```
Prior to this commit, neither `FormSubmissionDelegate` implementations
(`Navigator` nor `FrameController`) implemented the
`formSubmissionErrored` method.
By comparison, the [FrameController.requestErrored][] method
(implementing part of the …
> Forms: Log Submission failures to the console

- src/core/drive/form_submission.ts
- src/core/drive/navigator.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.ts
The `Navigator` class translates `<form method="get">` submissions into
`proposeVisit` calls, skipping the rest of the `FormSubmission`
architecture.
This commit adds support for declaring `[data-turbo-action="replace"]`
(or `"restore"` or `"advance"`) as a [Visit Action][]. Prior to this
commit, specifying a `Visit` action was limited to an `<a>`
click-initiated `Visit` only.
This can be useful for a `GET` form driven by auto-submission driving
the current page's URL, like a Typeahead autocomplete `<input
type="search">` field or a bounding-box scrolling Map. In those
scenarios, a series of `"advance"` page visits would yield an
essentially broken "Back" and "Forward" navigation experience.
[Visit Action]: https://turbo.hotwire.dev/handbook/drive#application-visits
> Support `data-turbo-action="..."` on Form Submits

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames/hello.html
- src/tests/functional/loading_tests.ts
Problem
---
Consider a `<turbo-frame>` element with `loading="lazy"`. Once it
becomes visible, the `AppearanceObserver` will delegate to the
`FrameController` to load its contents.
However, once visible, subsequent navigations of that frame will
continue to be deferred, since its `[loading]` attribute is still
deferred, in spite of the fact that the element is visible on that page.
Proposed change
---
This commit proposes to immediately navigate a `<turbo-frame>` element
with `[loading="eager"]` _or_ a `<turbo-frame>` element that has been
loaded previously.
Possible alternatives
---
As an alternative to adding another conditional to the guard clause,
could it be worthwhile to treat navigational changes driven by `<a>`
clicks or `<form>` submissions different from programatically …
> Navigate a lazy-loaded turbo-frame

- src/core/frames/frame_controller.ts
- src/core/url.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/frames/self.html
- src/tests/fixtures/test.js
- src/tests/functional/frame_tests.ts
- src/tests/helpers/functional_test_case.ts
Closes https://github.com/hotwired/turbo/issues/98
Closes https://github.com/hotwired/turbo/issues/182
When a `<turbo-frame>` element declares a `[src]` attribute that
references the URL the frame is loaded from, prevent an infinitely
looping chain of requests.
To do so, extend the `FrameElement.isActive` predicate to also check for
[Node.isConnected][].
[Node.isConnected]: https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected
> Prevent infinite looping when loading frames

- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Closes [#227][]
Adds a set of conditional guards to the
`FrameController.shouldInterceptFormSubmission()` method, similar to the
[Session.willSubmitForm()][] method, implementing a [identical guard
logic][]
[#227]: https://github.com/hotwired/turbo/issues/227
[Session.willSubmitForm()]: https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/session.ts#L157-L159
[identical guard logic]: https://github.com/hotwired/turbo/blob/8bce5f17cd697716600d3b34836365ebcdc04b3f/src/core/session.ts#L252-L259
> Skip form[data-turbo="false"] submissions in frame

- src/core/frames/frame_controller.ts
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
- src/tests/helpers/functional_test_case.ts
Closes [#223][]
When handling a `<form>` submission targeting a `<turbo-frame>` element
that results in a `303` redirect, update the `<turbo-frame src="...">`
to reflect the new location.
To account for the fact that `FrameController` instances are monitoring
changes to `<turbo-frame src="...">` via a Custom Elements
[attributeChangedCallback][], momentarily toggle that controller's
ability to respond to those changes to allow for modifying the `src`
attribute without triggering a redundant HTTP request.
Additionally, add coverage to ensure that navigating a `<turbo-frame>`
through an `<a>` sets the `[src]` attribute in way that is public to
the document.
[#223]: https://github.com/hotwired/turbo/issues/223
[attributeChangedCallback]: …
> Frames: Set `src` when a `<form>` redirects frame

- src/tests/fixtures/navigation.html
- src/tests/fixtures/one.html
- src/tests/fixtures/test.js
- src/tests/functional/navigation_tests.ts
- src/tests/helpers/turbo_drive_test_case.ts
Closes https://github.com/hotwired/turbo/issues/117
Closes https://github.com/hotwired/turbo/issues/159
---
While the original implementation change for this commit was covered
elsewhere, there is still value in the tests to add coverage for the
behavior.
> Add test coverage for toggling data-turbo-preview

- src/core/frames/frame_controller.ts
- src/elements/frame_element.ts
- src/tests/functional/frame_tests.ts
- src/tests/helpers/turbo_drive_test_case.ts
When a Turbo Frame declares the `[disabled]` attribute, prevent any
navigation.
Once removed, if a Turbo Frame's `[loading="eager"]` and `[src]` exists,
navigate the frame.
> Observe changes to turbo-frame[disabled]

- src/core/frames/frame_controller.ts
- src/http/fetch_request.ts
- src/tests/functional/form_submission_tests.ts
Closes https://github.com/hotwired/turbo/issues/86
Closes https://github.com/hotwired/turbo/pull/110
When submitting a Form that is within a `<turbo-frame>` or targets a
`<turbo-frame>`, ensure that the `Turbo-Frame` header is present.
Since the constructive-style
`FetchRequestDelegate.additionalHeadersForRequest()` was replaced by the
mutative style `FetchRequestDelegate.prepareHeadersForRequest()`, this
commit introduces a readonly `FetchRequestHeaders` property created at
constructor-time so that its values can be mutated prior to the
request's submission.
Co-authored-by: tleish <tleish@users.noreply.github.com>
> Prepare Frame Form Submission fetch headers

- src/core/frames/frame_controller.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/test.js
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
- src/tests/helpers/turbo_drive_test_case.ts
During the request lifecycle, `<turbo-frame>` elements will toggle the
`[busy]` boolean attribute to true when the request starts, and then
remove it when the request ends.
Additionally, form submissions were not triggering the same `[busy]` toggling behavior, so this commit adds coverage for that behavior as well.
This commit adds functional test coverage for that behavior.
> turbo-frame[busy] attribute

- src/core/streams/stream_actions.ts
- src/elements/stream_element.ts
- src/tests/unit/stream_element_tests.ts
Fixes #132
@dhh this implements Option C of https://github.com/hotwired/turbo/issues/132#issuecomment-813040051
When appending/prepending, children of the template may contain the same ID as children of the existing target.
_(this is common when using turbo-rails or other frameworks where the append/prepend action comes both as a result of the response to the original action and as a broadcasted action from a background job)_.
When this is the case, the generated result contains duplicate children ID which is undesirable.
This PR changes the behaviour of the append/prepend actions so that the existing children of the target which match the children of the template are removed before appending the template.
Assuming the following contrived example:
Target: 
```html
<ul id="vehicles">
<li …
```
> Remove target children with duplicate ID before append/prepend

- src/core/frames/link_interceptor.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Rails UJS offered a path to turn links into form submissions via the data-method attribute. This PR recreates that capability under data-turbo-method (but also with data-method for compatibility with existing apps built to Rails UJS). 
The link is turned into a form that's added next to the link in the dom, such that all the frame scopes still apply, and corresponding behavior is triggered.
For accessibility reasons, we should continue to promote buttons rather than method links, but this makes Hotwire much easier to fit into existing applications that were built to Rails UJS standards.
> Turn links with methods into form submissions

- src/core/drive/visit.ts
When there is no anchor but there is an element on the page with an empty `id` or `name` attribute, `scrollToAnchor` scrolls to that element.
This is because `getAnchor` returns an empty string but the current code checks for `null`.
> Fix check for anchor in `scrollToAnchor`

- CONTRIBUTING.md
As requested in #187 I have started on a contribution guide to lower the barrier for developers to contribute to the project.
I did not include information yet about the debugger port the is opened during the test suite as I have yet to figure out how that works myself.
> #187 Start the contribution guide

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/frames/form-redirect.html
- src/tests/fixtures/frames/form-redirected.html
- src/tests/functional/frame_tests.ts
This is my attempt at a fix based on discussion and the previous PR as well as adding a test for it.
The gist: A frame will only update/make a request if `currentURL` and `sourceURL` are different. `currentURL` was not get updated properly so it was still pointing to the previous value. If `sourceURL` changes back to the original URL of the frame, the values would match and result in the frame not navigating.
Example:
- Frame gets src set to "a". `sourceURL` and `currentURL` are set to "a"
- The frame's src is changed to "b". While `sourceURL` is updated, `currentURL` is still "a". Frame navigates to "b".
- The frame's src is changed back to "a". Because `currentURL` was never changed to "b", navigation doesn't happen because `sourceURL` == `currentURL`. 
Fixes #245 
Fixes #249 (I …
> Allow a frame to navigate to previous url

- src/core/session.ts
- src/observers/cache_observer.ts
- src/tests/fixtures/cache_observer.html
- src/tests/functional/cache_observer_tests.ts
- src/tests/functional/index.ts
Some content is inherently stale the moment you've shown it to users. Eg in Ruby on Rails it's common that you use flash messages to communicate a message from your controller to your users.
When a user navigates away and returns to the original page, turbo will briefly show cached content:
https://user-images.githubusercontent.com/440926/107358271-78aa4300-6ad3-11eb-8345-3da01cfe7e3d.mov
This PR adds a hook by adding `data-turbo-cache="false"` to individual dom elements to remove them from Turbo's cache.
--
_Originally posted about the issue in https://github.com/hotwired/turbo-rails/issues/117_
> Remove stale elements before cache

- src/core/session.ts
- src/tests/functional/visit_tests.ts
We don't need to go through proposeVisit, because the visit already passed that check to get into the history.
> History needs to visit with a restoration identifier to restore scroll position

- src/core/renderer.ts
PR #192 added support to evaluate `script` elements in turbo frames. I found out, that it worked for me only when CSP was disabled or sets with `unsafe_inline` for `script_src`.
This small change allows to use it when the CSP nonce generation is used in the application.
I am sorry, but I was not able to find a way how to write a proper test for it. Any help with that will be very welcomed. I only tested it locally with the latest Rails with this CSP setting:
```ruby
Rails.application.config.content_security_policy do |policy|
policy.script_src :self, :https
end
Rails.application.config.content_security_policy_nonce_generator = -> request { SecureRandom.base64(16) }
Rails.application.config.content_security_policy_nonce_directives = %w[script-src]
```
Thank you for any feedback or help …
> Copy CSP nonce to script element inside turbo frames

- src/core/drive/head_snapshot.ts
- src/tests/fixtures/additional_assets.html
- src/tests/fixtures/noscript.css
- src/tests/fixtures/test.css
- src/tests/functional/rendering_tests.ts
This pull request prevents Turbo from evaluating `<noscript>` elements inside the `<head>` element.
As a descendant of the `<head>` element, a `<noscript>` element can include `<style>` and `<link>` elements. This is useful for example, to show modals for script-enabled users and always to show modal contents for script-disabled users.
ref: [&lt;noscript&gt; - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript)
Currently, Turbo evaluates stylesheets inside `<head>` elements even though those are inside `<noscript>` elements. This causes unexpected style for script-enabled users after a page transition.
When Turbo requests, JavaScript is definitely enabled. So `<noscript>` elements can be safely ignored.
> Ignore noscript elements inside head

- src/core/frames/frame_controller.ts
- src/core/frames/link_interceptor.ts
- src/core/session.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/server.ts
This is the continuation of #277 that introduced `data-turbo-method`. Unfortunately it only worked within turbo-frames.
This PR aims to make it work globally.
> Make links with method work everywhere, not only inside turbo frames

- src/tests/functional/autofocus_tests.ts
- src/tests/functional/pausable_rendering_tests.ts
- src/tests/functional/pausable_requests_tests.ts
1. The autofocus test randomly fails locally and on CI. Extended sleep time to improve it.
2. Added missing sleep for pausable tests.
> Improve flaky tests

- src/core/index.ts
There are situations where you don't want the entire body to be replaced. One of the reasons would be when you're using 3rd party libraries that inject code (i.e. an iframe) such as Intercom or HelpScout, as this would result in the removal- and state-loss of their UI component every time you navigate using turbo drive.
Looking through previous issues it seems that there's no desire to add the ability to select a different node to render turbo drive responses into. So instead, it would be nice to be able to monkey-patch this functionality in so we can opt-out of this constraint. However, in order to do this we'll need access to PageRenderer, which currently isn't exported. This PR exports it.
> Export PageRenderer

- src/tests/functional/visit_tests.ts
TurboDriveTestCase maintains a eventLogChannel that acts as a cursor
for the page's window.eventLogs array. Before every test the
eventLogChannel is drained by reading all events and its internal
index (cursor) is updated accordingly.
The race was happening when we changed the page location and not
blocking on it: the eventLogChannel was draining the previous page
bumping its internal index. After the page was reload that index was
out of sync since the new page had a new, empty eventLogs array.
Order of events
* async location change
* draining eventLogChannel on the previous page
* actual location change
* eventLogChannel is out-of-sync
This was fixed as part of #289
> Avoid race between visit tests

- src/http/fetch_request.ts
- src/tests/functional/visit_tests.ts
Hello all and thank you for Turbo.
Although the `turbo:before-fetch-request` event includes the request's `fetchOptions` (method, headers, etc), it doesn't include the URL itself. With this patch applied you can access it with `event.detail.url`.
If it gets accepted I can send a PR to add a reference to the `events` documentation in https://github.com/hotwired/turbo-site/.
> Include url in `turbo:before-fetch-request` event

- CONTRIBUTING.md
- package.json
- src/tests/runner.js
Allow passing command-line options to the test runner like `--grep` and `--environment` to make development easier.
I used `arg` which is already a dependency (required by `ts-node`).
> Introduce test runner options

- src/core/session.ts
When developing the proof-of-concept for [animated page transitions using paused rendering](https://resonant-inky-replace.glitch.me/), it was useful to know whether a visit was a restoration or otherwise. For example, it felt weird to animate a Back restoration visit in the same way as an Advance visit.
This pull request adds the visit's `action` to the `turbo:visit` event to make this possible.
> Make visit action accessible from visit event

- src/elements/frame_element.ts
- src/tests/functional/loading_tests.ts
As proposed in #202, this PR adds a `.reload()` method on the frame that allows to refresh its content.
Open points:
* I am not happy with the test. It actually does not test anything interesting. I'd like the content of the frame to change upon reloading and verify that, but I have no clue on how to do that. A bit of help or an idea would be appreciated. I left it there to give an idea of what I wanted to do, but as of now, it could be removed.
* What if the frame has no src attribute? In my implementation, a call to `reload()` will simply have no effect. To me this is simple and stupid, so it should be fine.
> Add a "reload" method to the frame element

- src/core/view.ts
We can skip interception after preview inside the event handler. So no need to do it in core.
See the discussion here: https://github.com/hotwired/turbo/pull/314#issuecomment-881958039
> Fix rendering interception after preview

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/session.ts
- src/tests/functional/navigation_tests.ts
Do not trigger unexpected events on same-page visits. Fixes #321
> Prevent unexpected side-effects of same-page visit events.

- src/core/drive/navigator.ts
- src/core/snapshot.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.ts
Currently, if the location is `http://example.com#main`, and we call `Turbo.visit(location.toString())`, the page will just scroll to the anchor without reloading the page. This makes is impossible to refresh a current page via a Turbo visit.
Rather than checking for the presence of a URL hash, this pull request just checks that the hash has changed. If so, it's a same page visit.
/cc @jayohms
> Fix page loads when refreshing location with anchor

- src/core/drive/form_submission.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
This is a follow up PR based on the great work by @johnnyfreeman  https://github.com/hotwired/turbo/pull/266
Drive form submissions do not work as expected if there is a form field with `name="action"`.
For reference, the Mozilla docs describe the [Issues with Naming Elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#issues_with_naming_elements). Here's the relevant bit:
---
This PR first uses `getAttribute('action')` before checking `form.action`. We also typecheck `form.action` to make sure it is a string and not an element. 
If `getAttribute` and `form.action` don't return a value, we fall back to an empty string. 
It seems like `expandURL` falls back to `document.baseURI`, so using an empty string should might be ok? …
> Fix error with form inputs named action

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/view.ts
- src/tests/fixtures/422_tall.html
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/helpers/functional_test_case.ts
- src/tests/server.ts
In testing Turbo in my Rails app I noticed after submitting forms that were rejected by the server, the window position remain constant when the form was redrawn. This created a UX issue were if the errors were near the top of the form, outside of the viewport, it may be unclear to the user what happened.
This PR brings simply scrolls the viewport to the top once the error response is rendered . I'm using this in prod on my Rails app and so far it's behaving as expected.
This is my first contribution to a JS lib, so I just wanted to get a sense from the core team if this one-liner was the right way to solve this before I wrote any tests.
> Scroll to top after form submission rejection

- src/core/drive/navigator.ts
- src/core/native/adapter.ts
- src/core/native/browser_adapter.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/navigation_tests.ts
- src/tests/helpers/functional_test_case.ts
- src/tests/server.ts
- src/tests/unit/deprecated_adapter_support_test.ts
Fixes #61
Note: This PR is simply an extraction from the unmerged PR #164.
Currently when forms are submitted using Turbo Drive there is no progress bar shown when the request is taking a bit. This PR fixes that by bolting on two new formSubmission methods to the generic Adapter interface and implementing them in the browser adapter. 
While I know extending the adapter interface could make extra work for the `turbo-ios` and `turbo-android` maintainers, I think there might be enough differentiated behavior in form submissions to make separate methods a better choice in the long-term vs genericizing the `visitRequestStarted` and `visitRequestFinished` methods.
> Display progress bar on form submissions

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- intern.json
- src/tests/functional/navigation_tests.ts
With the introduction of Github Codespaces, it is easier than ever to contribute to an open source project. In my pursuit of fixing a bug in Turbo, I wanted to use a Codespace. In order to run the test suite, some additional tools are needed in the devcontainer:
- Java for starting a webserver
- Firefox for browser testing
- Chromium for browser testing
My goal is to successfully run `yarn test` after booting a Codespace. I'm running into some issues I don't know how to solve, so this is a WIP PR with a call for some help:
1. Firefox is green for all but one spec about the scroll position. 
```
× firefox on linux 5.4.0-1055-azure - NavigationTests - navigating back to anchored URL (0.783s)
AssertionError: scrolled to #main: expected false to be truthy
at NavigationTests.test navigating …
```
> Add Github Codespace configuration

- src/core/frames/frame_controller.ts
- src/tests/functional/frame_tests.ts
https://github.com/hotwired/turbo/pull/349 introduced a bug with reloading on reconnect after the first click: https://github.com/hotwired/turbo/pull/349#issuecomment-903564696
> Reset `reloadable` attribute on reconnect and on form submissions

- src/http/fetch_request.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.ts
- src/tests/server.ts
Closes #276, closes #253, closes #175.
This PR improves request abortion error handling. This will prevent page reloads on link double-clicks (it was caused by calling `this.delegate.requestErrored` on `AbortError`).
> Handle request abortion

- src/core/drive/navigator.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Closes #208, closes #234.
Call `View.renderError` when receiving server error (5XX) after form submission.
> Handle server errors for form submissions

- src/core/session.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Reverts hotwired/turbo#341. This breaks links within turbo frames as reported in #358.
CC @davidgil.
> Revert "Links with method not work if used inside another form"

- src/http/fetch_response.ts
- src/tests/fixtures/sample_short_response.html
- src/tests/fixtures/visit.html
- src/tests/functional/visit_tests.ts
Hi,
I detected a small bug during migrating from turbolinks to turbo. :)
It appears when he wants to get `responseHTML` or `responeText` on event: `turbo: before-fetch-response`
> Fix for get response html/text in locked body

- src/core/drive/form_submission.ts
- src/core/frames/frame_controller.ts
- src/http/fetch_request.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
This PR makes `turbo:before-fetch-request` and `turbo:before-fetch-response` events to fire on the respective form or frame element.
This way, we can easily attach event listeners to the desired elements, instead of listening for these events on the document.
- By adding the optional `target` parameter to the `FetchRequest`'s class contructor
- By passing the `FrameElement` to the `FetchRequest` constructor from `visit` method of `FrameController` class
- By passing the form element to the `FetchRequest` constructor inside `FormSubmission`'s class constructor
> Add the target element to turbo:before-fetch-(request | response) events

- src/tests/fixtures/frame_navigation.html
- src/tests/fixtures/frames.html
- src/tests/fixtures/one.html
- src/tests/functional/frame_navigation_tests.ts
- src/tests/functional/frame_tests.ts
Fixes #252: we wanted a new property to target the nearest frame.
As we read [this page](https://www.tagindex.net/html/frame/a_target.html) we realised that `target="_self"` is what we were looking after and not `target="_parent"` (which might still be a different option).
When we started implementing the tests for that, we realised that it's already possible to do that! 
Probably not on purpose but because by setting `data-turbo-target='an_id_that_does_not_exist'` simply overrides the default set in the parent frame (in our case `_top`) and always replaces the frame itself. Is this actually a bug or intentional?
We decided that the test implemented here is meaningful anyway and might work as regression test in case the current behaviour was unexpected.
Co-authored-by: @simon-isler
> Allow to set target="_self" in a link

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.ts
> Fix frame reloading from links/forms nested inside a turbo-frame

- src/polyfills/submit-event.ts
It came to my attention that mrujs also uses the submit-event polyfill (and im sure a number of other packages) and perhaps we should add a check if the submit-event polyfill already exists so we dont get the following error:
https://github.com/ParamagicDev/mrujs/issues/113
This behavior is fixed in mrujs `0.4.12` but will require Turbo to run their IIFE first so import order will matter (I think)
https://github.com/ParamagicDev/mrujs/pull/114
> fix: check if submit-event polyfill exists

- src/core/frames/frame_controller.ts
- src/core/frames/frame_redirector.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/frames/hello.html
- src/tests/functional/form_submission_tests.ts
Adds support for reading the value of `data-turbo-frame` from a
`submitter` (transmitted as part of the `SubmitEvent.submitter`
property) as if it were a `<button>` element's [formtarget][] attribute.
This change comes with an added benefit of meshing with Rails'
[button_to][] helper:
```ruby
button_to "Submit to turbo-frame#frame_id",
form: { data: { turbo_frame: "frame_id" } } # before
button_to "Submit to  turbo-frame#frame_id",
data: { turbo_frame: "frame_id" }           # after
```
[formtarget]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement
[button_to]: https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-button_to
> Read `data-turbo-frame` target from Submitter

- src/core/drive/head_snapshot.ts
- src/tests/fixtures/rendering.html
- src/tests/fixtures/tracked_nonce_change.html
- src/tests/functional/rendering_tests.ts
When navigating between pages that have tracked head elements with nonces, Turbo would erroneously perform a load instead of an advance every time, because the browser hides the nonce value in the DOM, while Turbo receives the raw request with the nonce in it from the server. 
Solution is to strip the nonces from all tracked elements when comparing the head signatures.
> Ignore nonces in tracked elements when comparing head signatures

- src/core/drive/head_snapshot.ts
This catches the check as to whether an element is new in addition to whether it is tracked.
Follow-up to #394.
> Strip nonce attribute when snapshot is created

- src/util.ts
It's possible for this not to be true if the target element has been removed from the dom between when a form submission was made and the response is processed. This can happen as a race condition when the same turbo stream removal is triggered by both websocket and server response.
> Target must be in the document.body to be the event emitter

- src/core/session.ts
I have an example of some styles breaking when a form is injected into the markup.
https://user-images.githubusercontent.com/77887/134426025-fca17045-9c33-4a42-9f3e-c90bdba39360.mp4
You can see the actions move to the right after clicking the "Undo" link. This is because the actions are spaced out using [TailwindCSS's spacing helpers](https://tailwindcss.com/docs/space), and the link has a `data-turbo-method` attribute which causes Turbo to create a form and insert it in the DOM before the link. So where there was previously:
```html
<div class="space-x-3">
<a data-turbo-method="delete" href="...">Undo</a>
<a>Dismiss</a>
</div>
```
I now have:
```html
<div class="space-x-3">
<form>...</form> 
<a data-turbo-method="delete" href="...">Undo</a>
<a>Dismiss</a>
</div>
```
---
One possible …
> Mark forms created for links with data-turbo-method as hidden

- src/core/session.ts
- src/tests/fixtures/drive_disabled.html
- src/tests/functional/drive_disabled_tests.ts
Fixes #392 
When you disable Turbo Drive wholesale with `Turbo.session.drive = false` and spot enable it on a form without a submit button with `data-turbo=true` Turbo Drive still wouldn't fire because it couldn't verify that the submitter (which was null) had a container where turbo was enabled.
This pulls in the fix @willcosgrove recommends as it's wise to never assume the DOM placement and logic for a submitter that is null.
> Allow Drive to submit a form when spot-enabled but submitter is null 

- src/globals.d.ts
- src/polyfills/submit-event.ts
Fixes #390 
This PR updates the Polyfill to work around the Safari 15 bug where the submitter property is sometimes null when a form is submitted with element of type button vs an element of type submit. More info https://bugs.webkit.org/show_bug.cgi?id=229660
> Update SubmitEvent Polyfill to Workaround Safari 15 bug

- src/core/frames/form_interceptor.ts
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.ts
#396 
The class LinkInterceptor checks if the target is a valid Element and if the closest turbo-frame matches the current turbo-frame. 
```javascript
class LinkInterceptor {
constructor(delegate, element) {
//...
if (this.respondsToEventTarget(event.target)) 
respondsToEventTarget(target) {
const element = target instanceof Element
? target
: target instanceof Node
? target.parentElement
: null;
return element && element.closest("turbo-frame, html") == this.element;
}
```
The FormInterceptor checks if the target is a HTMLFormElement, but does not check if the closest turbo-frame matches the current turbo-frame.
```javascript
class FormInterceptor {
constructor(delegate, element) {
//...
if (event.target instanceof HTMLFormElement) {
```
As a result, a nested turbo-frame will bubble up to …
> Fix form in nested turbo-frame with target=_top

- src/core/index.ts
- src/elements/frame_element.ts
- src/elements/stream_element.ts
again, was trying to get an understanding of this code base so had been documenting my understanding.
here's some jsdoc if its of any use. if its something you'd like to merge just let me know any rewording you want etc.
i know this project doesn't aim to be consumed by JS much, but the element jsdoc especially is useful for tooling which hints at the available properties/attrs of custom elements.
on that note, you may want to change the stream element to have identical 'mirrored' properties to its attributes just like the frame element does. so it can be configured by attributes _and_ by properties (and can then be documented).
> add jsdoc to exported components

- src/core/drive/navigator.ts
- src/core/session.ts
- src/core/url.ts
- src/tests/fixtures/drive.html
- src/tests/functional/drive_tests.ts
Currently, when calling `Turbo.visit("https://example.com", { action: "advance" })` , the site will not navigate to the `https://example.com` and in addition a number of errors pop up here:
Most of these errors have to do with trying to fetch cross-origin as well as adding history for a cross-origin url. This PR takes previous art from Turbolinks here:
https://github.com/turbolinks/turbolinks/blob/80cd172ed5b3a35eda85c58e428de9f1f1d06fc8/src/controller.ts#L70-L80
and uses previous art from Turbo's own link delegator here:
https://github.com/hotwired/turbo/blob/5982a679f19f9c745c51e85885e99069cf3d0c4a/src/core/session.ts#L334-L336
Unfortunately, I ran into multiple issues trying to get tests for this due to my chromedriver only supporting up to v92 and chrome itself being v94. I tried …
> fix: allow programmatic visits to go cross-origin

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.ts
Closes https://github.com/hotwired/turbo/issues/417
---
If there is an unresolved `FetchRequest` in-flight when navigating a
Turbo Frame, [abort][] its underlying [AbortController][] instance.
[abort]: https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort
[AbortController]: https://developer.mozilla.org/en-US/docs/Web/API/AbortController
> Frames: Abort prior requests during navigation

- src/polyfills/form-request-submit-polyfill.js
- src/polyfills/index.ts
So we can rely on requestSubmit everywhere and know it'll work on Safari.
> Add requestSubmit() polyfill by default

- src/core/frames/frame_controller.ts
- src/core/frames/frame_redirector.ts
- src/core/session.ts
- src/core/url.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Closes [#435][]
When observing `<form>` submissions (page-wide submissions, submissions
within a `<turbo-frame>`, or submissions targeting a `<turbo-frame>`),
ignore any with an `[action]` (or submitter `[formaction]`) attribute
that targets an external URL.
To determine whether or not a URL is "external", re-use the existing
`locationIsVisitable()` utility function used by the `Session` to
determine whether or not to navigate an `<a>` element.
The existing `locationIsVisitable()` calls depend on a "root" location
read from a `PageSnapshot` instance. The `FrameController` and
`FrameRedirector` do not have access to such an instance, so the `<meta
name="turbo-root" content="...">` element reading abstracted away by the
`PageSnapshot` is re-implemented across both call sites. When a …
> Ignore external `<form>` submissions

- src/core/frames/frame_controller.ts
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
Prior to this change, whenever a `<form>` submission drove a
`<turbo-frame>` element, `turbo:frame-render` events would fire but
`turbo:frame-load` events would not. The implementation to handle
navigations initiated by `[src]`-based attribute changes diverges from
the code paths that handle form submissions and `4xx` response
rendering.
Regardless of any plans to re-structure those code paths, it's important to ensure that
`turbo:frame-load` events fire regardless of how the `<turbo-frame>` was
navigated.
> Fire `turbo:frame-load` event during form submission

- src/core/drive/navigator.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.ts
Closes https://github.com/hotwired/turbo-ios/issues/44
Follow-up to https://github.com/hotwired/turbo/pull/231
---
This commit follows-up [#231][], which added `[data-turbo-action]`
support for idempotent form submissions to maintain parity with
`<a>`-initiated Visits.
These changes re-use the existent `Navigator.getActionForFormSubmission`
function to determine the value for the `VisitOptions.action` options.
[#231]: https://github.com/hotwired/turbo/pull/231
> Read `[data-turbo-action]` during Form Submissions

- src/core/drive/form_submission.ts
- src/tests/functional/form_submission_tests.ts
During a form submission, toggle the [disabled][] attribute on prior to
`turbo:submit-start`, and remove it prior to firing `turbo:submit-end`.
If callers need to control the submitter's [disabled][] attribute more
finely, they can declare listeners to do so.
Combined with CSS rules, consumer applications can hide and show
submission text similar to RailsUJS's support for `data-disable-with`:
```css
button                  .show-when-disabled { display: none; }
button[disabled]        .show-when-disabled { display: initial; }
button                  .show-when-enabled { display: initial; }
button[disabled]        .show-when-enabled { display: none; }
```
```html
<button>
<span class="show-when-enabled">Submit</span>
<span class="show-when-disabled">Submitting...</span>
</button>
``` …
> Toggle [disabled] on form submitter

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/frames/frame_controller.ts
- src/core/frames/frame_redirector.ts
- src/elements/frame_element.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/frames/frame.html
- src/tests/functional/frame_tests.ts
- src/util.ts
Closes https://github.com/hotwired/turbo/issues/50
Closes https://github.com/hotwired/turbo/issues/361
Closes https://github.com/hotwired/turbo/pull/167
---
Extend of built-in support for `<a>` elements with [data-turbo-action][]
(with `"replace"` or `"advance"`) to also encompass `<turbo-frame>`
navigations.
Account for the combination of of `[data-turbo-frame]` and
`[data-turbo-action]` to navigate the target `<turbo-frame>` _and_
navigate the page's history push state, supporting:
* `turbo-frame[data-turbo-action="..."]`
* `turbo-frame a[data-turbo-action="..."]`
* `a[data-turbo-frame="..."][data-turbo-action="..."]`
* `form[data-turbo-frame="..."][data-turbo-action="..."]`
* `form[data-turbo-frame="..."] button[data-turbo-action="..."]`
* `form …
> Push history state from frame navigations

- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/frames.html
- src/tests/fixtures/navigation.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
- src/tests/functional/navigation_tests.ts
- src/util.ts
Toggle the `[aria-busy="true"]` attribute to be present on a
`<turbo-frame>` element when its navigating, a `<form>` element when
it's submitting, or on the `<html>` element during any request, then
remove the attribute after the submission or navigation completes.
This is a change from the `turbo-frame[busy]` attribute, but aims to
achieve the same purpose. For the sake of backwards compatibility, Turbo
will continue to toggle the `[busy]` attribute during Frame navigations.
By unifying a single, consistent attribute, consumer applications can
use a single attribute CSS selector at different depths within their
page to hide or show loading indicators.
For example, consider a loading indication spinner animation within a
submit button that animates while a submission is in progress: …
> Toggle `[aria-busy="true"]` during requests

- src/core/frames/frame_controller.ts
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
- src/util.ts
Setting `[aria-busy="true"]` on the `<html>` element during a
`<turbo-frame>` navigation might be too aggressive given the frame's
value proposition of a compartmentalized request-response cycle. If
applications style the page based on `html[aria-busy="true"]`, having
that toggled during (eager or lazy) Frame loading could lead to a
disorienting experience.
If that isn't the case for applications, they can synchronize the
attribute themselves with a `MutationObserver`:
```js
const observer = new MutationObserver(([ { target } ]) => {
document.documentElement.setAttribute("aria-busy", target.busy)
}, { subtree: true, attributeFilter: ["busy"] })
observer.observe(document.body)
```
> Contain `[aria-busy]` toggling within Frames

- src/core/frames/form_interceptor.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Follow-up to https://github.com/hotwired/turbo/pull/3
---
When a `<form data-turbo-frame="...">` element is submitted, it's
handled by the `Frames/FormInterceptor` class instead of the
`FormSubmitObserver` class, which was originally fixed to cover this
behavior in [#3][].
This commit reproduces the fix so that it's consistent across `<form>`
elements, regardless of their targetting.
[#3]: https://github.com/hotwired/turbo/pull/3
> Skip form{,method}="dialog" when targetting frame

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/tests/functional/frame_tests.ts
[Follow-up to hotwired/turbo#398][].
The original implementation achieved the desired outcome: navigate the
page to reflect the URL of a `<turbo-frame>`.
Unfortunately, the `session.visit()` call happens late-enough that the
`<turbo-frame>` element's contents have already been updated. This means
that when navigating back or forward through the browser's History API,
the snapshots _already_ reflect the "new" frame's HTML. This means that
navigating back _won't change the page's HTML_.
To resolve that issue, expands the `VisitDelegate` to include a caching
callback, then expands the `VisitOptions` type to include a
`Partial<VisitDelegate>`. Throughout the lifecycle, a `Visit` will
delegate to _both_ its instance property and any present `VisitOption`
delegate hooks.
This commit aims to fix …
> Integrate Frame-to-Page Visits with Snapshot Cache

- src/core/drive/visit.ts
- src/core/frames/frame_controller.ts
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
The problem
---
By attempting to avoid unnecessary renders and events by introducing the
`willRender:` Visit option, the initial `<turbo-frame
data-turbo-action="...">` implementation was skipping several crucial
lifecycle hooks. For example, the resulting Visit would fire a
`turbo:render`, but would not fire a `turbo:load`. This left the
`<html>` element in an inconsistent state without cleaning up any
`[data-turbo-preview]` or `[aria-busy]` attribute modifications.
The solution
---
Forego the `willRender:` option, and instead propose a visit with a
pre-populated `statusCode`, `redirected`, and `responseHTML` value so
that the `Session` (including all of its hooks) can transparently handle it
the same as other `Visit` instances.
The result is much simpler than the original …
> Resolve Frame-to-Page Visit event ordering

- src/core/frames/frame_renderer.ts
Closes [#453]
---
While loading a matching `<turbo-frame>` element from a response body,
the `FrameController` "activates" it by invoking
[`FrameElement.connectedCallback()` after importing it into the document][activation].
During that activation, several event listeners are attached, including
some on the `document`.
Unfortunately, that `FrameElement.connectedCallback()` invocation is
never mirrored with a `FrameElement.disconnectedCallback()` invocation,
so the attached listeners are never detached, causing an accumulation.
This commit invokes the `disconnectedCallback()` after loaded element's
contents are extracted into the browser's document.
[#453]: https://github.com/hotwired/turbo/issues/453
[activation]: https://github.com/hotwired/turbo/blob/v7.1.0-rc.1/src/core/frames/frame_con …
> Disconnect loaded Frame Element while rendering

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
- src/tests/functional/navigation_tests.ts
Closes [446][].
When handling a `<form method="get" action="..."
data-turbo-frame="...">` submission targeting a `<turbo-frame>` element,
responses that don't redirect do not change the element's `[src]`
attribute.
Following the changes made in [424][], `<form>` submissions that result
in `GET` requests are handled the same as other form submissions in that
they fire `turbo:submit-start` and `turbo:submit-end` events. What
[424][] did not account for is navigations initiated by `<form
method="get">` submissions that _do not_ redirect.
In response to those requests, this commit adds two additional criteria
for updating the `<turbo-frame src="...">` attribute:
* the response's status code is [200 OK][], which is idempotent and does
not indicate a server-side state change (for example, like …
> Frames: handle `GET` form submissions

- src/core/drive/navigator.ts
- src/core/drive/page_renderer.ts
- src/core/drive/page_view.ts
- src/core/drive/visit.ts
- src/core/frames/frame_controller.ts
- src/core/renderer.ts
- src/core/session.ts
- src/elements/frame_element.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/test.js
- src/tests/functional/frame_tests.ts
The problem
---
The changes made in [444][] removed the `willRender:` Visit option in
favor of allowing Frame-to-Visit navigations to participate in the
entire Visit Rendering, Snapshot Caching, and History navigating
pipeline.
The way that the `willRender:` guard clause was removed caused new
issues in how Frame-to-Visit navigations were treated. Removing the
outer conditional without replacing it with matching checks elsewhere
has caused Frame-to-Visit navigations to re-render the entire page,
and losing the current contextual state like scroll, focus or anything
else that exists outside the `<turbo-frame>` element.
Similarly, the nature of the
`FrameController.proposeVisitIfNavigatedWithAction()` helper resulted in
an out-of-order dispatching of `turbo:` and `turbo:frame-` events, and …
> Preserve page state while promoting Frame-to-Visit

- src/core/frames/frame_controller.ts
- src/core/frames/frame_renderer.ts
- src/tests/functional/frame_tests.ts
Add test coverage for event listener leaking
===
Add test coverage to [hotwired/turbo#454][]. While the original fix was
important to ship, it was unclear how to guard against re-introducing
the leaks.
This commit introduces the `withoutChangingEventListenersCount()` test
helper to wrap a block within the test harness. While executing within
the block, the driven page's `document.addEventListener` and
`document.removeEventListener` functions are replaced with decorated
functions that increment and decrement a counter. At the start of the
block, capture and return how many times `addEventListener` has been
invoked without a matching `removeEventListener`. At the end, capture
and return the differential.
[hotwired/turbo#454]: https://github.com/hotwired/turbo/pull/454
Move the …
> Add test coverage for event listener leaking

- src/core/frames/form_interceptor.ts
- src/tests/functional/form_submission_tests.ts
Closes [hotwired/turbo#243][]
In tandem with [rails/rails#41960][] (which shipped as part of
`7.0.0.alpha2`), this commit modifies the `FormInterceptor` to ignore
`submit` events that have been cancelled.
Although it doesn't test the integration directly, the cancellation of
the `submit` event is what powers the ActiveStorage.js direct upload
asynchrony. Following a direct upload, ActiveStorage dispatches a
synthetic `submit` event, which the `FormInterceptor` will then respond
to.
[hotwired/turbo#243]: https://github.com/hotwired/turbo/issues/243
[rails/rails#41960]: https://github.com/rails/rails/pull/41960
> Frames: Ignore already cancelled `submit` events

- src/core/drive/form_submission.ts
- src/core/frames/frame_controller.ts
- src/http/fetch_request.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/navigation.html
- src/tests/fixtures/scroll_restoration.html
- src/tests/fixtures/visit.html
- src/tests/functional/frame_tests.ts
- src/tests/functional/navigation_tests.ts
- src/tests/functional/scroll_restoration_tests.ts
- src/tests/functional/visit_tests.ts
Closes [hotwired/turbo#456][]
The changes made in [hotwired/turbo#464][] resolved an issue in how
`GET` requests merged query parameters into their `URL` instance.
Unfortunately, the changes were too loosely scoped, and they affected
_all_ `GET` requests, including those initiated by `<a>` elements with
`[href]` attributes that declare search parameters directly (that *do
not* need to be "merged" into anything).
The [change][] made in [hotwired/turbo#464][] to conditionally include
the `FetchRequest.body` based on the request's verb enables the changes
made in this commit.
In response to that change, this commit moves the
`mergeFormDataEntries()` function out of the `FetchMethod` module and
into the `FormSubmission` class. Since merging _from_ `FormData`
instances _into_ a `URL` is a …
> Restore searchParams to Visit and Frame Navigation

- src/core/drive/progress_bar.ts
- src/tests/fixtures/rendering.html
- src/tests/functional/rendering_tests.ts
Progress Bar injects inline `<style />` element to page. However, when Content Security Policy is turned on and `nonce` is generated - Progress Bar element ignores that.
This PR fixes that and checks if `csp-nonce` is set in `meta` tags. Then it uses it to create inline style.
Update: I don't know why test is failing and is generating `<style />` without `nonce` being set. However, when testing manually - this fix works. I might need some help here from someone more experienced in writing JS tests.
> Progress Bar Won't Render if CSP is Turned On

- src/core/drive/progress_bar.ts
Many websites use z-index to display top bars, headers, staff bars, etc. 
When I tried to use Turbo on a site, I noticed this exact problem. Some developer somewhere had made a staff bar which has z-index set to `9999`. The Turbo progress bar wasn't visible. 
I considered changing this to `99999` (5 nines) to up the ante and make sure Turbo won this particular battle, but it doesn't win the war. Setting `z-index` to some arbitrarily high value is common practice, and often times is set to some N number of 9s value, such as `9999` or `99999` or `999999999`. It's hard to enforce a rule for developers to use some maximum value, and the usual response to something not working is just to tack another 9 on.
I propose we go nuclear, and set z-index to `2147483647` which I believe to be the …
> set turbo-progress-bar z-index to max value

- src/tests/fixtures/navigation.html
- src/tests/fixtures/rendering.html
- src/tests/functional/navigation_tests.ts
- src/tests/functional/rendering_tests.ts
Merging [hotwired/turbo#501][] into `main` introduced a [consistent
failure to the test suite][ci-failure]:
```
× firefox on linux 5.11.0-1022-azure - RenderingTests - progress bar inline style has nonce (0.32s)
458
AssertionError: displays progress bar: expected false to be truthy
459
at RenderingTests.test progress bar inline style has nonce @ src/tests/functional/rendering_tests.ts:24:16
460
at processTicksAndRejections @ internal/process/task_queues.js:97:5
461
at async RenderingTests.runTest @ src/tests/helpers/intern_test_case.ts:43:6
```
This commit re-structures the test to make the same assertion (replacing
the [script][] tagname with [style][]).
[script]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
[style]: …
> Resolve progress bar test suite failure

- .github/workflows/ci.yml
- package.json
- src/http/fetch_request.ts
- tsconfig.json
- yarn.lock
This upgrades known dependencies to their latest versions, and makes a few small changes to the `tsconfig` and `fetch_request` files to upgrade the failing TypeScript build.
> Upgrade all packages

- src/core/drive/page_renderer.ts
- src/core/drive/page_snapshot.ts
- src/tests/fixtures/html_attributes.html
- src/tests/fixtures/html_attributes_two.html
- src/tests/fixtures/one.html
- src/tests/fixtures/two.html
- src/tests/functional/drive_disabled_tests.ts
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/navigation_tests.ts
- src/tests/functional/visit_tests.ts
- src/tests/helpers/turbo_drive_test_case.ts
Turbo only replaces the `<body>` and updates the `<head>` when navigating, ignoring possible changes to the `<html>` element, like classes or `data-*` attributes.
With this change, Turbo will update the `<html>` when navigating through pages.
> Update <html> element attributes when navigating

- src/core/drive/page_renderer.ts
- src/core/native/adapter.ts
- src/core/native/browser_adapter.ts
- src/core/renderer.ts
- src/core/session.ts
- src/core/view.ts
- src/tests/fixtures/test.js
- src/tests/functional/rendering_tests.ts
I feel like we are missing an event fired when the page is going to be hard reloaded. With `turbo:reload` users will be able to listen to **why** their Turbo navigations are causing reloads instead of soft-navigation. That will help users track the data and improve their apps.
> Add a `turbo:reload` event that returns the reason why turbo needed to do a hard reload.

- src/core/index.ts
Hello, thank you for Turbo, I really love it! This PR is basically the exact same motivation as exposing PageRenderer in #305
With this, its trivial to replace frame rendering with a Virtual DOM like so:
```javascript
import morphdom from "morphdom";
import { FrameRenderer } from "@hotwired/turbo";
FrameRenderer.prototype.loadFrameElement = function() {
morphdom(this.currentElement, this.newElement, {
childrenOnly: true,
onBeforeElUpdated: function(fromEl, toEl) {
return !fromEl.isEqualNode(toEl);
}
});
}
```
I don't believe there's an alternative, at present. If a `before-frame-render` event gets added, like in #431, it might be possible to do it through that.
> Expose FrameRenderer so we can extend its behavior, e.g. vDOM.

- src/core/drive/form_submission.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
This pull request makes so that you can use different `data-turbo-confirm` on each submitter inside your form, instead of allowing only one `data-confirm` per form.
Problem: If you're nested inside a form, you can't use `button_to` because you'd end up with a nested form, which is invalid and discarded by the browser.
So, how one would accomplish a UI like the following?
That delete button is inside a form. A `button_to` there isn't allowed. 
However, as @seanpdoyle greatly points [here](https://thoughtbot.com/blog/dynamic-forms-with-turbo), the browser spec allows you to change the default `action` and `method` of the form **on the submitter**, by using `formaction` and `formmethod` attributes **on the button itself**.
So you could go for this:
```erb
<%= f.button formaction: …
```
> Make data-turbo-confirm work with multiple submitters inside a form

- .github/workflows/ci.yml
Node 12 will reach EOL at the end of April. Many Github actions have recently updated to use Node 16 (the Active LTS) and moved off of 12.
Updated `actions/checkout`, `actions/setup-node` and `actions/cache` in ci.yml to their most recent versions which are ran/built against Node 16. Also, chnged the node-version used in Github actions to 16.
The dev container appears to already be set up to use Ndoe 16.
> Update Github actions to use Node 16

- src/core/drive/form_submission.ts
- src/core/index.ts
- src/tests/functional/form_submission_tests.ts
The browser's `confirm` is synchronous and waits for a boolean. This is really convenient, but makes it painful to implement a custom confirm modal in Boostrap, Tailwind, etc.
This PR adds `await` so a custom `confirm` can return a promise that waits until the user confirms or cancels the operation.
The overridden confirm method simply needs to return a Promise that resolves to `true` or `false.
```js
Turbo.setConfirmMethod(() => {
return new Promise((resolve, reject) => {
// show modal
// on confirm, resolve(true)
// on cancel, resolve(false)
})
})
```
Closes #522
Example of it in action:
https://user-images.githubusercontent.com/67093/151271318-5034bbff-6b24-462f-89f7-8e6e3f8d0466.mp4
> Await for confirm method results

- src/core/drive/page_renderer.ts
- src/core/native/browser_adapter.ts
- src/core/session.ts
- src/tests/functional/form_submission_tests.ts
Generated: execute `yarn lint --fix`
===
Follow-up to [hotwired/turbo#573][].
ESLint support was recently merged and integrated in to the Continuous
Integration checks, but excluded several existing linting violations.
This commit's diff was generated by executing `yarn lint --fix`.
These violations were discovered when rebasing [hotwired/turbo#436][].
Once this is passing and merged, these changes will be rebased into that
branch's changeset.
[hotwired/turbo#573]: https://github.com/hotwired/turbo/pull/573
[hotwired/turbo#436]: https://github.com/hotwired/turbo/pull/436/files
Resolve failing `FormSubmissionTest`
===
There is a race condition in the `FormSubmissionTest` file's coverage
for confirmation. If evaluated quickly enough, the test's assertions
might be checked before the …
> Generated: execute `yarn lint --fix`

- src/core/index.ts
- src/core/session.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
In large application upgrading from turbolinks to turbo requires all
forms that use `render` to return validations errors needs to be
updated with `status: :unprocessable_entity` to as in #39 to.
This makes it hard to upgrade as you ether have to have a single PR that
upgrades all form (when you have over 400 forms is pretty risky) or
disable all forms which again can be risky if you miss one before
completing the upgrade.
There are other options but it would be great if you can could do this in
turbo and save hours of work.
To allow this I've added a `formMode` to the session so you can change
the behaviour of turbo and how it interacts with forms.
The mode is set via the `Tubro.setFormMode` option and can be set to one
of 3 options:
- "on" all forms will be submitted with turbo, this is …
> Add option to disable turbo for form or optin to forms.

- src/core/drive/page_view.ts
- src/core/drive/visit.ts
- src/tests/fixtures/rendering.html
- src/tests/functional/rendering_tests.ts
Potential solution for https://github.com/hotwired/turbo/issues/387
This change updates how we handle scrolling when the page gets reloaded due to a `reload` directive.
I'm not sure if this is the proper way to gate the behavior but I was able to confirm the fix manual using the fixtures html files.
I'd also love to hear if there is a good way write a test for this fix.
https://user-images.githubusercontent.com/2181356/163845443-0c025ea8-5c5c-465e-9c6e-c886164bea72.mov
https://user-images.githubusercontent.com/2181356/163845321-6354af64-b160-47ae-86fc-922e112614c1.mov
> Don't scroll to top of page on reload

- src/core/drive/navigator.ts
- src/core/drive/page_view.ts
- src/tests/functional/navigation_tests.ts
- src/tests/functional/rendering_tests.ts
Silent Visits don't dispatch events. A Visit is deemed to be silent if its location is on the current page. Prior to this commit, this is determined by checking the last rendered location. This approach can result in false positives if a Visit is interrupted and never gets rendered. For example, tapping a link, then immediately navigating back, will be incorrectly considered a same-page visit. Checking the previous location using window.location is also not possible on Back/Forward because it is changed _before_ the popstate event, so by the time a new Visit is created, the location has already changed.
This commit accurately compares the last visited location by storing a reference to the lastVisit on the Navigator, falling back to the View's lastRenderedLocation.
Fixes #594
> Prevent silent restoration visits when previous visit request is in-flight

- src/core/bardo.ts
- src/core/renderer.ts
- src/core/snapshot.ts
- src/tests/fixtures/frames/hello.html
- src/tests/fixtures/rendering.html
- src/tests/functional/rendering_tests.ts
- src/tests/helpers/functional_test_case.ts
Problem
---
When an interactive element like an `<input>`, `<select>`, `<textarea>`,
or `<button>` has an `[id]` attribute and is marked as
`[data-turbo-permanent]`, the element and its internal state is
preserved _except_ for its focus state.
Imagine a search form:
```html
<form>
<label for="search">Search</label>
<input type="search" id="search" name="q" data-turbo-permanent>
</form>
```
When typing a query into the box and submitting the `<form>` by
<kbd>enter</kbd>, the request is submitted, the page transitions, the
element retains its `[value]` attribute, but focus is lost.
Solution
---
When transposing a permanent element during a `Renderer` descendant's
(e.g. [PageRenderer](./src/core/drive/page_renderer.ts), [ErrorRenderer](./src/core/drive/error_renderer.ts), or …
> Restore focus when transposing Permanent Elements

- src/elements/index.ts
There are instances when turbo attempts to create the frame and stream
elements when they have already been registered. This is easily
reproducible in development when using webpacker by following these steps:
* Make a change to any file that webpacker compiles.
* Click a turbo enabled link.
* Boom.
When Turbo replaces the page it appears as if it reloads the Turbo
library and attempts to create the custom elements again. I have also
observed this behavior in my production app via my exception monitoring
service, but have been unable to reproduce this behavior in production
on my own.
This change simply checks for the existence of the custom element prior
to to attempting to define it. The `get` method used here explicitly
returns `undefined` when the element does not yet exist so it is …
> Defensively create custom turbo elements

- src/polyfills/submit-event.ts
The submit-event polyfill was being interpreted by TSC as a script and not a module.
This caused all the declarations there to be treated as global in the exported types.
Fixes #523
> Do not declare global types/constants

- src/core/session.ts
IE issue (edge) : FormElement.method attribute only accepts "get|post". To my surprise, it seems to be the expected behaviour from the spec: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#form-submission-attributes. TLDR ;
```
The method and formmethod content attributes are [enumerated attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#enumerated-attribute) with the following keywords and states:
The keyword get, mapping to the state GET, indicating the HTTP GET method.
The keyword post, mapping to the state POST, indicating the HTTP POST method.
The keyword dialog, mapping to the state dialog, indicating that submitting the [form](https://html.spec.whatwg.org/multipage/forms.html#the-form-element) is intended to close the …
```
> fix(ie/edge): form.method='delete', raises Invalid argument.

- src/core/frames/frame_controller.ts
- src/core/frames/frame_redirector.ts
- src/elements/frame_element.ts
- src/tests/fixtures/loading.html
- src/tests/functional/frame_tests.ts
- src/tests/functional/loading_tests.ts
Closes https://github.com/hotwired/turbo/issues/429
---
Introduce the `<turbo-frame complete>` boolean attribute. The attribute's
absence indicates that the frame has not yet been loaded, and is ready
to be navigated. Its presence means that the contents of the frame have
been fetch from its `[src]` attribute.
Encoding the load state into the element's HTML aims to integrate with
Snapshot caching. Once a frame is loaded, navigating away and then
restoring a page's state from an Historical Snapshot should preserve the
fact that the contents are already loaded.
For both `eager` and `lazy` loaded frames, changing the element's
`[src]` attribute (directly via JavaScript, or by clicking an `<a>`
element or submitting a `<form>` element) will remove the `[loaded]`
attribute. Eager-loaded frames …
> Expose Frame load state via `[complete]` attribute

- src/core/drive/form_submission.ts
- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/util.ts
Turbo Streams are normally supported only for [non-GET requests][0]. However there are cases where Turbo Streams responses to GET requests are useful.
This commit adds the ability to use Turbo Streams with specific GET requests by setting `data-turbo-stream="true"` on a form or link.
[0]: https://github.com/hotwired/turbo/pull/52
> Allow Turbo Streams with GET via `data-turbo-stream`

- src/core/url.ts
Before we fully resolve #519, we can sort out the main hurt from this, which seems to be .php extensions.
> Add .php as a valid isHTML extension

- src/core/drive/form_submission.ts
- src/core/frames/link_interceptor.ts
- src/core/index.ts
- src/core/session.ts
- src/elements/stream_element.ts
- src/http/fetch_request.ts
- src/observers/cache_observer.ts
- src/observers/stream_observer.ts
- src/util.ts
Various `turbo:`-prefixed events are dispatched as [CustomEvent][]
instances with data encoded into the [detail][] property.
In TypeScript, that property is encoded as `any`, but the `CustomEvent`
type is generic (i.e. `CustomEvent<T>`) where the generic Type argument
describes the structure of the `detail` key.
This commit introduces types that extend from `CustomEvent` for each
event, and exports them from `/core/index.ts`, which is exported from
`/index.ts` in-turn.
In practice, there are no changes to the implementation. However,
TypeScript consumers of the package can import the types. At the same
time, the internal implementation can depend on the types to ensure
consistency throughout.
[CustomEvent]: https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent
[detail]: …
> Export Type declarations for `turbo:` events

- src/core/frames/frame_renderer.ts
The default behavior can be pretty jarring depending on your use case but this allows people to specify the scroll behavior when autoscrolling.
> Allow frames to scroll smoothly into view

- src/core/cache.ts
- src/core/drive/form_submission.ts
- src/core/drive/progress_bar.ts
- src/core/index.ts
- src/core/renderer.ts
- src/util.ts
This Pull Request introduces a `Cache` class which exposes an API as `Turbo.cache` that can be used to control the value of the `turbo-cache-control` meta element form the client-side.
Most of the times you just need to the set the value of the `turbo-cache-control` meta element from the server-side when you are responding to your regular HTML request, based on if you want that page to be cached or not.
I encountered a few use-cases in a couple of apps I worked on where you dynamically want to set the cache control behavior after a certain action happened on the client (i.e. you don't want to show remaining artifacts of a finished animation in a later visit, but if the animation wasn't triggered you still want that page to be properly cached).
You can achieve a similar behavior by …
> Introduce client-side Turbo Cache Control API

- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/observers/form_link_interceptor.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
In an effort to match the patterns established by `LinkInterceptor`
and `FormInterceptor`, this commit introduces a
`FormLinkInterceptor` and `FormLinkInterceptorDelegate`.
Behind the scenes, the `FormLinkInterceptor` relies on an instance of
the `LinkInterceptor` to intervene in `<a>` element clicks when
`[data-turbo-method]` or `[data-turbo-stream]` are present. When those
clicks are detected, it creates a `<form hidden>` element, attaches it
to the document, delegates to a `FormLinkInterceptorDelegate` to map
the `<a>` element's attributes to the `<form>` element, submits the form
through the polyfilled [HTMLFormElement.requestSubmit][] method, then
removes the `<form>` from the document.
The `Session` serves as a `FormLinkInterceptorDelegate`, making sure
to start and stop the …
> Introduce `FormLinkInterceptor`

- src/core/drive/form_submission.ts
- src/observers/form_link_interceptor.ts
- src/tests/fixtures/form.html
- src/util.ts
Replace equality checks for `[data-turbo-stream="true"]` with presence
checks for `[data-turbo-stream]` to more closely match the canonical
behavior for [boolean HTML attributes][].
Turbo already supports other boolean attributes like
`[data-turbo-permanent]` and `[data-turbo-confirm]`, so
`[data-turbo-stream]` should match the precedent.
[boolean HTML attributes]: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#boolean_attributes
> Treat `[data-turbo-stream]` as boolean attribute

- src/observers/form_submit_observer.ts
- src/observers/link_click_observer.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/navigation.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/navigation_tests.ts
Skip intercepting `<a>` element clicks or `<form>` element submissions
when they target an `<iframe>`. This occurs when an `<a>` declares a
[target][a-target], when a `<form>` declares a [target][form-target], or
a `<form>` element's submitting `<button>` element declares a
[formtarget][formtarget].
[a-target]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target
[form-target]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-target
[formtarget]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formtarget
> Ensure Turbo does not interfere with IFrames

- src/core/frames/frame_controller.ts
- src/core/frames/frame_renderer.ts
- src/elements/frame_element.ts
- src/tests/functional/frame_tests.ts
- src/tests/functional/loading_tests.ts
Follow-up to [hotwired/turbo#441][]
Depends on [hotwired/turbo#487][]
Closes https://github.com/hotwired/turbo/issues/472
---
When caching Snapshots during a `Visit`, elements are not cached until
after the `turbo:before-cache` event fires. This affords client
applications with an opportunity to disconnect and deconstruct and
JavaScript state, and provides an opportunity to encode that state into
the HTML so that it can survive the caching process.
The timing of the construction of the `SnapshotSubstitution` instance
occurs too early in the frame rendering process: the `<turbo-frame>`
descendants have not been disconnected. The handling of the
`<turbo-frame>` caching is already an exception from the norm.
Unfortunately, the current implementation is caching _too early_ in the
process. If …
> Frame Visits: Cache Snapshot later in process

- .github/workflows/ci.yml
- src/core/drive/error_renderer.ts
- src/core/drive/page_renderer.ts
- src/core/drive/page_view.ts
- src/core/frames/frame_controller.ts
- src/core/frames/frame_renderer.ts
- src/core/frames/frame_view.ts
- src/core/renderer.ts
- src/core/session.ts
- src/core/view.ts
- src/tests/fixtures/form.html
- src/tests/functional/rendering_tests.ts
Renderer: Extract `renderElement()`
===
For each renderer (`PageRenderer`, `ErrorRenderer`, `FrameRenderer`)
extract their rendering logic into a class-`static-` property named
`renderElement()`. That function accepts two arguments: the first is the
current version of the element being rendered, the second is the new
version of the element being rendered.
The `PageRenderer` and `ErrorRenderer` types are genericized to accept
`HTMLBodyElement` instances. The `FrameRenderer` generics accept a
`FrameElement` instance. This means that the `renderElement()` function
shares the same class-level generics.
Extract `ViewRenderOptions`
===
Introduce the `ViewRenderOptions<E extends Element>` to store the
`resume()` function dispatched with the `turbo:before-render` event.
Future commits will add …
> Support custom rendering in `turbo:before{-frame,}-render` events

- src/observers/form_link_interceptor.ts
- src/tests/fixtures/pausable_rendering.html
- src/tests/functional/pausable_rendering_tests.ts
Follow-up to https://github.com/hotwired/turbo/pull/431
Support for the `turbo:before-frame-render` event relies on the same
underlying infrastructure as the `turbo:before-render` event (i.e. the
`Renderer` abstract class). As a result of re-using that abstraction,
listeners for the `turbo:before-frame-render` event can also leverage
the `detail.resume` function in the same way to handle asynchronous
rendering.
The changes made in [hotwired/turbo#431][] excluded test coverage for
that behavior. This commit adds that coverage to guard against
regressions in that behvaior.
[hotwired/turbo#431]: https://github.com/hotwired/turbo/pull/431
> Add tests for pausable Frame Rendering

- src/core/index.ts
- src/tests/functional/stream_tests.ts
Closes https://github.com/hotwired/turbo/pull/478
Closes https://github.com/hotwired/turbo/pull/477
As an alternative to continuing to introduce support for more varied and
specialized `<turbo-stream action="...">` values, this commit exports
the `StreamActions` module from the root-module in order to provide
applications with direct access.
Applications can add new actions or override existing actions, so long
as they adhere to the `StreamAction` interface: a function whose `this`
context is an instance of `StreamElement`.
> Custom Actions: Export `StreamActions` module

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/navigation_tests.ts
Closes #193
When handling a form submission, turbo clears cache but then re-creates a cache of the current page before navigating to the new page.
```javascript
async formSubmissionSucceededWithResponse(formSubmission: FormSubmission, fetchResponse: FetchResponse) {
if (formSubmission == this.formSubmission) {
///...
if (responseHTML) {
if (formSubmission.method != FetchMethod.get) {
this.view.clearSnapshotCache() //<= clear cache
}
///...
this.proposeVisit(fetchResponse.location, visitOptions) //<= recreates cache
}
}
}
```
> Clear cache on non-GET form submit

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/index.ts
- src/core/native/adapter.ts
- src/core/native/browser_adapter.ts
- src/core/renderer.ts
- src/core/session.ts
- src/core/types.ts
- src/tests/functional/visit_tests.ts
- src/tests/unit/deprecated_adapter_support_test.ts
When consumer applications navigate through the `Turbo.visit`, return a
`Promise<void>` that will resolve when the visit is complete.
If a visit fails or is cancelled, the `Promise` will be rejected.
To achieve this behavior, extract the `ResolvingFunctions<T>` type
from the `Renderer` class into the shared `src/core/types.ts` module.
Following the pattern established by `Renderer` instances, add a
`promise: Promise` property to the `Visit` class, and use that `Promise`
to assign a `resolvingFunctions: ResolvingFunctions<void>` property to
make the underlying `resolve()` and `reject()` calls available to the
`Visit`.
When a `Visit` completes successfully, call
`this.resolvingFunctions.resolve()`. When it fails or is canceled from
the outside, call `this.resolvingFunctions.reject()`.
> Return `Promise<void>` from `Turbo.visit`

- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/observers/form_link_click_observer.ts
- src/observers/link_click_observer.ts
- src/tests/functional/form_submission_tests.ts
The `LinkInterceptor` class contains some Frame-specific checks that
were at the root of `<a data-turbo-method="...">` element clicks
submitting multiple HTTP requests.
To resolve the underlying issue, this commit changes the
`FormLinkInterceptor` class to rely on an instance of
`LinkClickObserver` instead of `LinkInterceptor`.
In order to make that possible, this commit also extends the
`LinkClickObserver` to accept a second argument to server as the
[EventTarget][] for the `click` event listeners. As a consumer, the
`FormLinkInterceptor` instances attached to `<turbo-frame>` element
scope their listeners to the element, while the `Session`'s
`FormLinkInterceptor` instance attaches a catch-all listener to the
`window`.
Since this commit changes the underlying event listening mechanism, …
> Prevent form links from submitting multiple requests

- src/core/frames/frame_controller.ts
- src/core/frames/frame_renderer.ts
- src/tests/functional/frame_navigation_tests.ts
Closes https://github.com/hotwired/turbo/issues/643
First, rename the `FrameRendererDelegate.frameExtracted` callback method
to `willRenderFrame`, then pass along both the _current_ frame and the
_new_ frame as arguments.
Next, in the `FrameController.willRenderFrame` callback, assign the
`previousFrameElement` property (used elsewhere in the
`visitCachedSnapshot` callback) to contain the contents of the _current_
frame, instead of the _new_ frame.
> Resolve Frame Visit caching issue

- src/core/snapshot.ts
- src/tests/fixtures/autofocus-inert.html
- src/tests/fixtures/autofocus.html
- src/tests/functional/autofocus_tests.ts
- src/tests/functional/frame_tests.ts
Closes [hotwired/turbo#546][]
According to the specification, there is an [algorithm][] for
determining the [focusable area][], that is, the elements with the
`[autofocus]` attribute that can receive focus:
> Elements that meet all the following criteria:
> * the element's [tabindex][] value is non-null, or the element is determined by the user agent to be focusable;
> * the element is either not a shadow host, or has a shadow root whose delegates focus is false;
> * the element is not actually [disabled][];
> * the element is not [inert][];
> * the element is either being rendered or being used as relevant canvas fallback content.
This commit extends the `Snapshot.firstAutofocusableElement` to
programmatically determine the focusable area based on the available
attributes, including …
> Do not autofocus inert or hidden elements

- src/core/drive/form_submission.ts
- src/tests/functional/form_submission_tests.ts
Closes [hotwired/turbo#272][]
Do not exclude a `<form>` submitter's `[name]` attribute from the
encoded `FormData` instance, even if a `[value]` is not specified.
Instead, encode the value as an empty string if a `[value]` attribute is
unspecified.
The existing tests included a [button][] to exercise this exclusion
behavior. Their assertions were incorrect, so this commit changes them
to reflect the proper behavior.
[button]: https://github.com/hotwired/turbo/blob/1563ebbfa3f4c8530b334e194da9db630163041b/src/tests/fixtures/form.html#L103
[hotwired/turbo#272]: https://github.com/hotwired/turbo/issues/272#issuecomment-1198671657
> Encode Form Submitter `[name]` into submission

- src/core/drive/visit.ts
- src/core/session.ts
- src/elements/frame_element.ts
- src/tests/functional/frame_tests.ts
Add support for driving a `<turbo-frame>` element from a
`Turbo.visit(...)` call.
Internally, Turbo has some constraints for finding and driving a
`<turbo-frame>` element, namely that it has an `[id]` attribute and that
it is not marked with a `[disabled]` attribute.
Supporting `Turbo.visit` calls that specify a `frame:` option
provide an opportunity to encapsulate those details from callers while
still providing element finding utility.
> `Turbo.visit(..., { frame: "frame" })`

- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/tests/fixtures/drive_disabled.html
- src/tests/functional/drive_disabled_tests.ts
https://github.com/hotwired/turbo/pull/196 introduced the ability to disable Drive by default. An unintentional side-effect was that it also disabled Frame by default. Every Frame needed the data-turbo attribute to be enabled: `<turbo-frame data-turbo="true">`. This makes it so that `Turbo.session.drive = false` only affects Drive.
On top of the logic change, we rename the Session methods to remove the Drive vocabulary.
---
@gregschmit Ping as the author of #196. Am I right to assume that this was an un unintentional side-effect?
> Disabling Drive keeps Frames default behaviour

- src/core/drive/visit.ts
- src/tests/fixtures/scroll/one.html
- src/tests/fixtures/scroll/two.html
- src/tests/fixtures/visit.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/visit_tests.ts
Closes https://github.com/hotwired/turbo/issues/400
When processing a `Visit`, invoke `Visit.performScroll()` while loading
a response, loading a Snapshot, or executing a same-page anchor
navigation. After in-lining those calls to more appropriate points in
the Visit lifecycle, this commit removes the `performScroll()` call from
the `Visit.render()` method.
> Perform scrolling prior to Visit completion

- src/core/session.ts
The Pull Request #648 refactored the function name of
`session.elementDriveEnabled()` to `session.elementIsNavigatable()`.
This Pull Request fixes an old function reference which kept the library
from building successfully.
> Change `elementDriveEnabled()` to `elementIsNavigatable()`

- src/core/drive/error_renderer.ts
- src/core/drive/head_snapshot.ts
- src/core/drive/page_renderer.ts
- src/core/frames/frame_renderer.ts
- src/core/renderer.ts
- src/core/streams/stream_message.ts
- src/observers/stream_observer.ts
- src/tests/fixtures/stream.html
- src/tests/functional/stream_tests.ts
- src/util.ts
Closes https://github.com/hotwired/turbo/pull/527
When a `<turbo-stream>` element connects to the document, "activate"
each `<script>` element by re-creating it as an element owned by the
`document` instance.
To re-use the existing `Renderer.createdScriptElement`, this commit
extracts that logic to the `src/util.ts` module, and renames it to
`activateScriptElement`. Then, we replace each
`this.createdScriptElement` call site with a call to
`activateScriptElement`.
Along with that change, this commit changes the signature to expect an
[HTMLScriptElement][] instance,
Finally, as part of adding test coverage for the new behavior, this
commit re-structures existing tests to be more particular about their
expectations, and to throw failure messages that provide more clarity. …
> Activate `<script>` in Turbo Streams

- src/core/index.ts
- src/core/session.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/form_mode.html
- src/tests/functional/form_mode_tests.ts
- src/tests/functional/form_submission_tests.ts
Follow-up to https://github.com/hotwired/turbo/pull/655
Follow-up to https://github.com/hotwired/turbo/pull/419
This commit splits out a `form_mode_tests.ts` module separate from
`form_submission_tests.ts`, along with a `form_mode.html` fixture file.
Next, add test fixtures and test coverage for more thorough coverage of
form mode, namely scenarios that submit a form without a submitter (for
example, typing into an `<input type="text">` and pressing
<kbd>enter</kbd>.
Next, the `Turbo.setFormMode()` should be particular about its
argument's value. This commit introduces a `FormMode = "on" | "off" |
"optin"` type.
Finally, rename `submitterIsNavigatable` to `submissionIsNavigatable`,
and pass the `HTMLFormElement` and optional `HTMLElement` as a pair of
arguments.
> Expand `Turbo.setFormMode` guards

- src/core/drive/form_submission.ts
- src/core/drive/visit.ts
- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/http/fetch_request.ts
- src/observers/form_link_click_observer.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/visit.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/visit_tests.ts
The initial implementation of the `data-turbo-stream` attribute worked
by treating requests with that attribute as form submissions (which
would be `GET` form submissions, unless a different method type was
indicated).
This allowed us to include the `data-turbo-stream` logic in
`FormSubmission`, which was responsible for properly setting the
`Accept` header.
However, there are some downsides to submitting the requests as form
submissions. For example, a `GET` form submission does not include the
search portion of the URL. Additionally, servers are free to respond to
`data-turbo-stream` requests with plain HTML responses, and in that case
we don't want Turbo's handling of the response to differ from what it
would have been if the `data-turbo-stream` attribute wasn't present.
This commit …
> Don't convert `data-turbo-stream` links to forms

- src/elements/frame_element.ts
- src/tests/functional/loading_tests.ts
- src/tests/functional/navigation_tests.ts
Following the pattern established by `Turbo.visit(...)` and
`Turbo.visit(..., { frame: "..." })`, return the `FrameElement.loaded`
promise from calls to `FrameElement.reload()`.
That way, callers can block on it:
```js
const frame = document.getElementById("my-frame")
await frame.reload()
// ...
```
> Return `Promise<void>` from `FrameElement.reload`

- src/elements/stream_element.ts
- src/tests/fixtures/stream.html
- src/tests/fixtures/test.js
- src/tests/functional/loading_tests.ts
- src/tests/functional/stream_tests.ts
Since the `turbo:before-stream-render` event is dispatched _before_ the
`<turbo-stream>` element is connected to the document, it isn't possible
to dispatch the event with the element as its `Event.target` property.
To work around that constraint, dispatch the reference as
`CustomEvent.detail.newStream` (named in the same way as `newBody` for
`turbo:before-render` and `newFrame` for `turbo:before-frame-render`).
> Dispatch `turbo:before-stream-render` with reference to `<turbo-stream>`

- src/core/drive/page_snapshot.ts
- src/tests/fixtures/rendering.html
- src/tests/functional/rendering_tests.ts
Re-submission of https://github.com/hotwired/turbo/pull/70
This change will save the values of `<input>`s, `<textarea>`s, and
`<select>`s when creating a snapshot so that when you navigate back or
forward in history, form fields will not be reset.
This behavior was already present prior to [5dfc79e][] for `<input>`s
and `<textarea>`s but not `<select>`s (see
[turbolinks/turbolinks#238][]).
[5dfc79e]: https://github.com/hotwired/turbo/commit/5dfc79ee2feba441ea9c9b486009d08336e78d76
[turbolinks/turbolinks#238]: https://github.com/turbolinks/turbolinks/issues/238
> Preserve input values in cache

- CONTRIBUTING.md
- README.md
A missing back-tick is at the root of a presentation issue that's
obscuring guidance on how to introduce test dependencies.
> Fix Markdown Syntax typo in CONTRIBUTING.md

- src/core/session.ts
- src/tests/functional/frame_tests.ts
After re-considering a comment on [hotwired/turbo#445][], this commit
re-purposes the response HTML from the `FetchResponse` instance, instead
of issuing a follow-up HTTP request.
[hotwired/turbo#445]: https://github.com/hotwired/turbo/pull/445#discussion_r934776811
> `turbo:frame-missing`: Re-use `FetchResponse` HTML

- src/observers/form_link_click_observer.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/test.js
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
When an `<a>` element annotated with `[data-turbo-method]` is clicked,
Turbo Drive creates, appends, submits, and removes a `<form>` element
behind the scenes.
Unfortunately, prior to this commit, the `<form>` element is submitted
then removed synchronously and immediately. This means that by the time
the `submit` events (and resulting `turbo:before-fetch-request` and
`turbo:submit-start` events) bubble up through the document, the
`<form>` element is already disconnected.
In its absence, the `document.documentElement` serves as the event's
target.
This commit changes that process to defer the elements removal until
_after_ it dispatches a `turbo:submit-end` event.
The result is that the element is present throughout all the events, and
is accessible through `event.target`.
> Form Link Submissions: Don't remove `<form>` until submission is complete

- src/core/drive/form_submission.ts
- src/core/index.ts
When overriding a `<form>` submission's confirmation method, also yield
the `FormSubmission.submitter` along with the message string and
`HTMLFormElement`.
> Add `submitter` to `Turbo.setConfirmMethod` callback

- src/core/drive/visit.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/cache_observer_tests.ts
When redirecting to a page that contains elements marked with
`[data-turbo-cache="false"]`, those elements are removed _before_ the
initial render, instead of _after_ the render and _before_ the page is
cached.
This behavior seems to have stemmed from [hotwired/turbo#516][], which
was shipped in response to [hotwired/turbo#515][].
As an alternative to the `willRender: false` option passed to
`this.adapter.visitProposedToLocation` in `Visit.followRedirect`, the
implementation can instead [rely on the presence of the
`turbo-frame[complete]`][comment] to guard against double fetching.
To guard against regressions, this commit adds coverage for the unwanted
behavior by redirecting from `navigation.html` to `cache_observer.html`,
and asserting the presence of a `[data-turbo-cache="false"]` …
> Bugfix: Redirects and `[data-turbo-cache=false]`

- src/core/session.ts
- src/tests/fixtures/visit.html
- src/tests/functional/visit_tests.ts
- src/tests/helpers/page.ts
- src/tests/server.ts
Normally when following a link Turbo sets `[aria-busy="true"]` on the
document element. When the visit is complete, that attribute is removed.
However, when using `[data-turbo-stream]` to request a stream response
to a link, there is no visit to complete. That presented as a bug where
`aria-busy` was set at the start of the operation, but never cleared.
To solve this, we avoid setting the `aria-busy` attribute for links that
have a `data-turbo-stream` attribute.
> `data-turbo-stream` links should not set aria-busy

- src/core/session.ts
The console was showing this warning when navigating:
Empty string passed to getElementById().
It's harmless, but a little noisy. This change rewrites the statement
that was causing it, to avoid the warning.
> Prevent empty string warning

- src/core/drive/head_snapshot.ts
[`element.tagName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName) always returns the elements tag name in all uppercase so we needed to cast it to all lower-case in order to fit our needs. 
In contrast, [`element.localName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/localName) returns the actual tag HTML name, so this is more accurate.
Since we are already using `element.localName` in a few other places in the codebase and because of it's good browser-support it's much more preferable to use.
> Use `element.localName` over `element.tagName.toLowerCase()`

- package.json
- yarn.lock
This Pull Request upgrades TypeScript to 4.8.2, analog to https://github.com/hotwired/stimulus/pull/583.
> Upgrade TypeScript to 4.8

- src/core/index.ts
- src/core/streams/stream_actions.ts
- src/elements/index.ts
- src/http/index.ts
- src/index.ts
When working with TypeScript in applications and libraries in can be quite frustrating to get the right types, especially when a library doesn't export all the required types.
Therefore this Pull Request exports the types and classes for the Custom Elements and Stream Actions so they can be used in applications and libraries without the need to redefine the types manually.
I also re-organized to exports for the `http` subfolder, since those types were exported from the core subfolder, which technically shouldn't need to care about the exports of other subfolders.
> Export Custom Elements and Stream Action Types

- src/observers/form_link_click_observer.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.ts
As I described in https://github.com/hotwired/turbo-rails/issues/359 `link_to` ignores `data-turbo-action` in combination with `data-turbo-method`.
Original error was found in `convertLinkWithMethodClickToFormSubmission` but it was overwritten by https://github.com/hotwired/turbo/pull/631. Unfortunately the `data-turbo-action` for `link_to` is still missing.
I added the `data-turbo-action` setting to `FormLinkInterceptor` in the same way as `data-turbo-confirm` and added a test  for it.
> Add support for data-turbo-action to link_to 

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/session.ts
- src/http/fetch_request.ts
- src/tests/functional/navigation_tests.ts
In a similar vein to #367, this pull request dispatches `turbo:visit`, `turbo:before-visit`, `turbo:before-fetch-request`, and `turbo:before-fetch-response` on the initiator link or form (where applicable), rather than solely on the `html` element.
**Why?** When developing libraries that build on top of Turbo, it'd be nice to customise behaviour based on HTML attributes of the clicked link or submitted form. For example, if I were building an animation library and wished to disable a transition when clicking a particular element, I could do:
```html
<a href="…" data-animate="false">Do not animate me</a>
```
I could then use `event.target.dataset.animate` in the `turbo:visit` event to conditionally animate.
Other examples are mentioned in #99.
Closes #99
> Dispatch visit events on the initiator link or form

- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.ts
Closes https://github.com/hotwired/turbo/issues/670
Re-use the existing `2xx` and `3xx` behavior for a response to handle
error responses. When the frame is missing from the page (likely for
error pages like `404`), dispatch a `turbo:frame-missing` event.
Alongside that behavior, yield the [Response][] instance and a
`Turbo.visit`-like callback that can transform the `Response` instance
into a `Visit`. It also accepts all the arguments that the `Turbo.visit`
call normally does.
When the event is not canceled, treat the `Response` as a Visit. When
the event **is** canceled, let the listener handle it.
[Response]: https://developer.mozilla.org/en-US/docs/Web/API/Response
> `turbo:frame-missing`: Dispatch for 4xx and 5xx

- src/core/drive/form_submission.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
- src/util.ts
Prior to this commit, declaring `[data-turbo-stream]` on a `<form>`
element with `[method=get]` would opt-into Turbo Stream support for the
response.
This commit extends that same support to `<form>` elements declared
_without_ the `[data-turbo-stream]` attribute that are submitted by
`<button>` or `<input type="submit">` elements that declare the
`[data-turbo-stream]` attribute.
> Opt-into Turbo Stream `GET` from Form submitter

- src/core/session.ts
- src/core/snapshot.ts
- src/core/streams/stream_message_renderer.ts
- src/tests/functional/navigation_tests.ts
- src/tests/functional/rendering_tests.ts
Closes https://github.com/hotwired/turbo/issues/623
Refactor the `Snapshot` implementation to make the permanent element
finding code re-usable outside that module.
Then, introduce the `StreamMessageRenderer` class, and re-use that code.
The `StreamMessageRenderer` class also implements `BardoDelegate`, and
relies on `Bardo.preservingPermanentElements` to manage elements across
their `<turbo-stream>` rendering lifespan.
> Turbo Streams: Preserve permanent elements

- src/elements/stream_element.ts
- src/tests/fixtures/stream.html
- src/tests/fixtures/test.js
- src/tests/functional/stream_tests.ts
- src/tests/helpers/page.ts
- src/tests/server.ts
Follow-up to https://github.com/hotwired/turbo/pull/479
Related to https://github.com/hotwired/turbo-site/pull/107
As an alternative to exposing an otherwise private and internal
`StreamActions` "class", support custom `<turbo-stream action="...">`
values the same way as custom `<turbo-frame>` rendering or `<body>`
rendering: as part of its `turbo:before-render-stream` event.
For example, if Turbo were to rename `StreamActions` to something else,
it would need to continue to export `StreamActions` publicly for the
sake of backwards compatibility. By depending on an event listener
instead, client applications are insulated from any internal restructuring.
To change how Turbo renders the document during page rendering, client
applications declare a `turbo:before-render` event listener that …
> Add `render` to `turbo:before-stream-render` event

- src/core/drive/visit.ts
Removed the redundant `identifier` property on the `Visit` class.
> Remove unused property `identifier`

- src/core/drive/form_submission.ts
- src/core/frames/frame_controller.ts
- src/core/index.ts
- src/core/session.ts
- src/http/fetch_request.ts
- src/http/index.ts
- src/tests/fixtures/form.html
- src/tests/fixtures/visit.html
- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_navigation_tests.ts
- src/tests/functional/visit_tests.ts
Follow-up to https://github.com/hotwired/turbo/pull/640
Related to https://github.com/hotwired/turbo-site/pull/110
When a `Visit` results in a `fetch` error (like when the browser is
offline), dispatch a `turbo:fetch-request-error` event in the same style
as `<turbo-frame>`- and `<form>`-initiated `fetch` errors.
For the sake of consistency, also make the `TurboFetchRequestErrorEvent`
cancelable.
Along with the implementation change, this commit also adds test
coverage to ensure that the `Event.target` is correct for
`<turbo-frame>` and `<form>` error events.
> Dispatch `turbo:fetch-request-error` during Visits

- src/core/index.ts
- src/tests/functional/frame_tests.ts
- src/tests/helpers/page.ts
- src/tests/unit/export_tests.ts
- src/tests/unit/index.ts
Frame Missing Tests: Wait for `turbo:render`
===
One of the `turbo:frame-missing` event tests is flaky since the
assertions execute without first waiting for a synchronizing event. This
commit changes the test to wait until a `turbo:render` event is
dispatched before making its assertions.
Scrolling Tests: Increase scrollY threshold
===
Tests are often flaky when exercising scrolling. More often than not,
Firefox scrolls to within _exactly_ 2 Y units.
This commit changes the `isScrolledToSelector` boolean to treat a 2 unit
difference as within the threshold.
Add test coverage for exports
===
Introduce the `src/tests/unit/export_tests.ts` module to cover what's
exported from the `src/index.ts` module, including both Turbo-prefixed
classes and objects and functions accessible as the …
> Address CI Test Flakiness

- src/core/drive/visit.ts
This property is required by turbo-ios, so removing it causes crashes within that library.
E.g. https://github.com/hotwired/turbo-ios/blob/main/Source/WebView/WebViewBridge.swift#L129
This reverts commit d81e24db77da05f53c6ab3c66e2620574c9e08c9.
> Reintroduce `Visit` `identifier` property

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/session.ts
- src/http/fetch_request.ts
- src/tests/functional/navigation_tests.ts
The inclusion of the `initiator` in `VisitOptions` causes a JS crash in the Turbo iOS adapter.
This is because Turbo iOS's implementation of `visitProposedToLocation` relies on being able to pass the entire options struct to native code. Initiator is an `Element`, which can't be passed in this way, resulting in a `DataCloneError` exception.
There is some discussion on this [GitHub issue][]. This PR reverts the change for the moment, until we have an implementation of it that works with all adapters.
[GitHub issue]: https://github.com/hotwired/turbo/issues/720
This reverts commit 887181796e8d5586de89c70327f31e9a81dcfec2.
> Revert "Dispatch visit events on the initiator link or form (#695)"

- src/core/drive/navigator.ts
- src/core/drive/visit.ts
- src/core/index.ts
- src/core/native/adapter.ts
- src/core/native/browser_adapter.ts
- src/core/renderer.ts
- src/core/session.ts
- src/core/types.ts
- src/tests/functional/visit_tests.ts
- src/tests/unit/deprecated_adapter_support_test.ts
Since #650, errors are present in the console whenever initiating a visit causes cancellation of the previous visit.
Reported in:
- https://github.com/hotwired/turbo/issues/706
- https://github.com/hotwired/turbo/issues/716
Reverting until a solution is found for the errors.
This reverts commit aeeaae8edb5f6ec6ef6b19eaf93dc060a1e67b10.
> Revert "Return `Promise<void>` from `Turbo.visit` (#650)"

- src/tests/functional/visit_tests.ts
With the reverting of [hotwired/turbo#695][] (merged as [hotwired/turbo#723][]), the "Visit with network error" test coverage was missed in the diff.
Prior to the revert, the test was listening for
`turbo:fetch-request-error` events dispatched on the _link_ that was clicked. Since that's no longer the case, this commit changes the test to listen for `turbo:fetch-request-error` that bubble up to the document.
[hotwired/turbo#695]: https://github.com/hotwired/turbo/pull/695
[hotwired/turbo#723]: https://github.com/hotwired/turbo/pull/723
> CI: Restore passing tests

- src/core/frames/frame_controller.ts
- src/core/frames/frame_redirector.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/test.js
- src/tests/functional/frame_tests.ts
- src/tests/functional/visit_tests.ts
- src/tests/helpers/page.ts
Closes https://github.com/hotwired/turbo/issues/726
Prior to this commit, clicking on `<a>` elements nested within
`<turbo-frame>` elements, or `<a>` elements that drive `<turbo-frame>`
elements did not dispatch `turbo:click` events in the same way that they
did before [hotwired/turbo#412][].
This commit re-instates those events as part of the `FrameController`
and `FrameRedirector` implementations for the `willFollowLinkToLocation`
methods they define as part of the `LinkClickObserverDelegate`
interface.
To be consistent with the existing `turbo:click` dispatch behavior, and
to guard against introducing similar regressions in the future, this
commit also adds test coverage for falling back to page-wide navigations
when `turbo:click` events are canceled.
In support of those changes, …
> Fix: Dispatch `turbo:click` when driving a Frame

- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.ts
- src/tests/helpers/page.ts
Closes https://github.com/hotwired/turbo/issues/727
Add test coverage to ensure that an `<a>` element click or `<form>` element submission nested within a `<turbo-frame>` _does not_ toggle `[aria-busy]` or `[busy]` on the `turbo-frame` if the navigation is targeting `_top` (with `[data-turbo-frame="_top"]`).
> Don't toggle `turbo-frame[busy]` when navigating `_top`

- playwright.config.ts
[Configure Playwright][] to retry a failed test at least twice before considering it failed. This should help cut down on CI flakiness.
[Configure Playwright]: https://playwright.dev/docs/test-configuration
> Configure Playwright to retry failed tests

- src/core/frames/frame_controller.ts
- src/elements/frame_element.ts
- src/tests/functional/frame_tests.ts
Closes https://github.com/hotwired/turbo/issues/739
Issue #739 mentions the issue at the root of the unexpected behavior:
> The reason is that `reload()` calls `this.removeAttribute("complete")`
> and the frame watches attribute changes and calls
> `this.loadSourceURL()` when the “complete” attribute is removed.
This commit resolves the issue in several steps.
First, add the `sourceURLReloaded()` callback to the `FrameElementDelegate` interface.
Next, move the `FrameElement.reload()` implementation from `FrameElement.reload()` to the `FrameController.sourceURLReloaded()`.
Finally, wrap the implementation's call to
`this.element.removeAttribute("complete")` within a `ignoringChangesToAttribute("complete", () => ...)` block so that the change to the attribute is temporarily ignored.
> Fix double `before-fetch-request` dispatch during reload

- src/core/drive/page_view.ts
- src/core/drive/visit.ts
- src/core/frames/frame_controller.ts
- src/tests/functional/frame_navigation_tests.ts
- src/tests/functional/frame_tests.ts
Closes https://github.com/hotwired/turbo/issues/745
Before this change, when a promoted frame finished its navigation, a visit was started and the visit would add a new PageSnapshot to the cache. The problem is that this snapshot was looking at a page that was already modified by the frame navigation, so the snapshot cache would be incorrect.
With this proposed change, we are taking a PageSnapshot as soon as the frame navigation starts, so we guarantee that the page hasn't been modified yet. Then, I'm passing this snapshot forward to the Visit and using it as the correct cache instead of calculating a new one.
> Cache PageSnapshot with original HTML from the frame's page

- src/core/frames/frame_controller.ts
- src/elements/frame_element.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
Closes https://github.com/hotwired/turbo/issues/747
Prior to this commit, `<turbo-frame>` elements navigated by `[data-turbo-frame]` attributes were not promoted into Visits if navigation initiator (a `<form>` element, for example) had another `<turbo-frame>` as its ancestor.
To resolve that issue, this commit adds the
`proposeVisitIfNavigatedWithAction` method to the `FrameElementDelegate` interface.
Instead of tracking _which_ `FrameElement` would navigate as a `Visit` through an internal `frame?: FrameElement` property, the `FrameController` methods **reach through** the `FrameElement` instance that's resolved by the `FrameController.findFrameElement` method to delegate navigation promotion to **that frame's delegate** instead of to itself.
> Resolve Issue #747

- src/core/native/browser_adapter.ts
- src/tests/fixtures/rendering.html
- src/tests/functional/rendering_tests.ts
- src/tests/server.ts
When a form submission fails with a client error, the response from the form replaces the current page content. In Turbo 7.1, whenever this replacement would affect resources marked with `data-turbo-track="reload"`, a reload of the page is triggered instead.
In 7.2.0, we do not perform this reload. Instead, the form's response is discarded. This happens because the content replacement does not occur during a visit, and so we have no new location to reload.
This difference can affect situations like expired sessions, where reloading the page would cause a new session to be established. If we instead allow the response to be discarded, actions can fail silently.
This commit changes the behaviour to reload the current page when `reload` is called outside of a current visit, in order to match …
> Reload page if failed form changes tracked content

- src/core/drive/visit.ts
- src/tests/functional/navigation_tests.ts
Closes https://github.com/hotwired/turbo/issues/762
Changes made in [hotwired/turbo#601][] had unintended side-effects that prevented same-page anchor navigations from writing to the history.
This commit adds a call to `Visit.updateHistory()` within `Visit.goToSamePageAnchor()` along with coverage in `src/tests/functional/navigation_tests.ts` to guard against future regressions.
[hotwired/turbo#601]: https://github.com/hotwired/turbo/pull/601
> Update history during same-page Visits

- src/core/drive/navigator.ts
In [#595][] the logic for determining whether a visit is a "same page" visit was changed. Previously we were comparing the new location with the current location. In #595 we began comparing with the location of the last visit that was started.
This works great when all the visits are web visits. However, it introduced some problems with apps using the native adapters. In native apps, navigations can be a combination of native screens and WebView navigations, which means that we can't rely on the last visit having been sent.
This manifests as failing navigations in certain situations, such as navigating back from a native modal to a WebView. It also caused some problems restoring scroll positions when navigating back from one WebView to another.
Restoring the original logic prevents these …
> Check last rendered location for same-page visits

- src/core/frames/frame_controller.ts
- src/observers/appearance_observer.ts
- src/tests/fixtures/frame_navigation.html
- src/tests/functional/frame_navigation_tests.ts
Prior to this commit, `<turbo-frame>` elements navigated via the `AppearanceObserver` (powered by the [loading=lazy][] attribute) were not accounting for their [data-turbo-action][] attributes.
To resolve that issue, this commit changes the `AppearanceObserver` and `AppearanceObserverDelegate` to utilize a parameterized `<T extends Element>` type so that the delegate callbacks can be invoked with `FrameElement` references. With those changes in place, this commit changes the `FrameController.elementAppearedInViewport` callback's invocation to prepare a `PageSnapshot` and attempt to `proposeVisitIfNavigatedWithAction`.
[loading=lazy]: https://turbo.hotwired.dev/reference/frames#lazy-loaded-frame
[data-turbo-action]: https://turbo.hotwired.dev/reference/frames#frame-that-promotes-navigations …
> Fix: Promoting lazy-loaded Frames

- src/core/drive/page_renderer.ts
Resolves #719 
When turbo loads a page, the current behavior is to remove and replace all provisional head elements.  This would include the title tag, meta tags, and link tags to icons, fonts and manifest.json.  This can lead to additional http requests as demonstrated below:  
https://user-images.githubusercontent.com/1790447/193615680-850b415e-5e99-4cc3-ba37-f9c5da353404.mp4
This PR merges the elements instead providing a cleaner page load experience and preventing these potential additional requests.
https://user-images.githubusercontent.com/1790447/193615692-ce90c1c1-91d8-4d78-8350-6839d16b8aac.mp4
**Unit test note:**
I was not able to get the test suite running and encountered this issue:
```
Tunnel started
BUG: suiteEnd was received for invalid session
```
If this PR has potential, …
> Merge in remaining header elements (eg: link icons, manifest, meta and title)

- src/tests/functional/form_submission_tests.ts
- src/tests/functional/frame_tests.ts
- src/tests/functional/loading_tests.ts
- src/tests/functional/navigation_tests.ts
- src/tests/functional/ujs_tests.ts
This is an entirely test-suite focused changeset.
The `noNextEventNamed`, `noNextEventOnTarget`, and
`noNextAttributeMutationNamed` test utility functions are named similarly to `nextEventNamed`, `nextEventOnTarget`, and `nextAttributeMutationNamed` helpers, but their behavior has one major subtle difference: they need to be wrapped in an assertion to fail.
For example, if a `noNextEventNamed(page, "turbo:load")` is invoked and there **is not** a `turbo:load` event to be read from the logs, the tests will wait indefinitely (until they time out). A timeout signals a failure, and the suite will fail. In the case of the `noNext`-prefixed versions, the absence of an entry in the logs will return `false` immediately. If the calling test does not make an assertion about the return value, it …
> Wrap `noNext`-prefixed test helpers in assertions

- src/core/drive/navigator.ts
- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/core/types.ts
- src/observers/form_link_click_observer.ts
- src/util.ts
The logic for reading an `Action` from a list of `Element` instances'
`[data-turbo-action]` attribute is still scattered across several
modules, in spite of the `getVisitAction` declared in the `util` module.
This commit replaces duplicate implementations of the `getVisitAction`
method with the utility function.
With those calls added, the `isAction` type checking utility is only
ever invoked by `getVisitAction`, so this commit moves its
implementation to the `util` module, and removes all other invocations.
> Re-use getVisitAction utility function

- src/core/drive/form_submission.ts
- src/core/drive/visit.ts
- src/core/frames/frame_controller.ts
- src/http/fetch_request.ts
With the introduction of `FetchRequest.acceptResponseType()` in [hotwired/turbo#647][], the
`FetchRequestDelegate.prepareHeadersForRequest` callback interacts with more than just the `FetchRequestHeaders` instance passes as its first argument.
Additionally, every implementation of the `FetchRequestDelegate` interface implements the `prepareHeadersForRequest` method, so the fact that it's listed as optional and invoked with a guard clause are unnecessary.
This commit renames the method to `prepareRequest`, reduces the signature to a single `FetchRequest` argument, and no longer declares it as a conditional property on the interface.
[hotwired/turbo#647]: https://github.com/hotwired/turbo/pull/647/files#diff-d4ee4683f7121e24a87566ef6854ee6090ee723a5299430338f5602febea8c1f
> Simplify `FetchRequestDelegate.prepareHeadersForRequest`

- src/core/bardo.ts
- src/core/drive/page_renderer.ts
- src/core/renderer.ts
- src/tests/functional/rendering_tests.ts
Since https://github.com/hotwired/turbo/pull/431, turbo allows users to customize the render function they want to use, but when an user defines an async function that requires some kind of wait, turbo's timing gets messed up and it fires events before the render actually happened.
With these changes, Turbo will correctly handle async render functions, properly waiting for it to finish before continuing the lifecycle.
> Allow users to define an async custom render function

- package.json
- yarn.lock
Our [CI][] is currently failing while executing `yarn run playwright install --with-deps`.
This commit updates the dependency in an effort to resolve whatever underlying dependency issues are causing the failure.
[CI]: https://github.com/hotwired/turbo/actions/runs/3664875382/jobs/6195570624#step:6:1
> Update `@playwright/test` dependency

- package.json
- src/core/renderer.ts
- yarn.lock
Closes [hotwired/turbo#812][]
The order of the arguments in the `Render` signature are incorrect, and [were introduced in that incorrect order][incorrect].
Luckily, the default implementations and the tests that exercise that feature are in the correct order.
The signature's argument order was inspired by
[morphdom's](https://github.com/patrick-steele-idem/morphdom#usage), with the latter argument serving as overrides for the prior argument.
Custom rendering isn't yet covered by Turbo's documentation website, so we have an opportunity to document it thoroughly and correctly, starting with TypeScript's understanding of the interface.
[hotwired/turbo#812]: https://github.com/hotwired/turbo/issues/812
[incorrect]: https://github.com/hotwired/turbo/pull/431/files#diff-d554b20c605a72c68b2d429ff …
> Correct `Render<E>` method signature argument order

- src/tests/fixtures/frame_navigation.html
- src/tests/fixtures/navigation.html
- src/tests/fixtures/test.js
- src/tests/functional/frame_navigation_tests.ts
- src/util.ts
Fixes #801.
This issue seems to be caused by the fact that events fired from inside the Shadow DOM won't propagate across the shadow DOM boundary into the standard DOM.
Normally, the turbo frame listens to the `turbo:click` event in the `LinkInterceptor`:
https://github.com/hotwired/turbo/blob/27384ecf1a22afacccc96cf01864fc6a82fa8cc0/src/core/frames/link_interceptor.ts#L20
And a link click will fire a `turbo:click` event that is eventually handled by the turbo frame link interceptor:
https://github.com/hotwired/turbo/blob/27384ecf1a22afacccc96cf01864fc6a82fa8cc0/src/core/session.ts#L329-L333
However, when the target link is in the shadow DOM, like declared in this PR, the event wouldn't reach the turbo frame link interceptor.
This could be fixed by specifying `composed: true`, so the …
> Allow for listening to turbo events raised from within the Shadow DOM

- src/core/streams/stream_actions.ts
This method does not exist in older versions of safari (only 14+). This
meand a polyfill would be required in order to use turbo when using the
update action. In order to stop this, we replace the call to this
function with native code.
> Ensure turbo no longer uses replaceChildren

- src/core/frames/frame_controller.ts
Frames that use `data-turbo-action` to promote their navigations to page visits require cache snapshots to be taken prior to them loading, in order for those snapshots to be accurate.
However snapshots can be expensive to create for complex pages. In cases where a frame is *not* being promoted, we can avoid taking that snapshot.
This helps with some performance issues observed when using frames on very large pages.
/cc @afcapel
> Only snapshot frame visits that have actions

- src/core/session.ts
- src/observers/link_click_observer.ts
- src/tests/fixtures/drive_disabled.html
- src/tests/fixtures/navigation.html
- src/tests/fixtures/test.js
- src/tests/functional/drive_disabled_tests.ts
- src/tests/functional/navigation_tests.ts
- src/util.ts
This PR adds better support for the Shadow DOM integration. Right now, Turbo fails to find the closest link when the click target is within the shadow DOM but the link target is not in the same shadow DOM.
This PR changes the `findLinkFromClickTarget` function so that it can cross the boundary and continues to reverse-traverse until it gets out of the shadow roots.
> Add better support for shadow DOM

- src/tests/fixtures/rendering.html
- src/tests/functional/rendering_tests.ts
Introduce a beat-long delay to reduce test flakiness from a race condition between the initial `page.click` and the subsequent `page.evaluate` calls.
For an example of the flakiness, this message was copied from a [CI failure on hotwired/turbo#430][]:
```
1) [chrome] › rendering_tests.ts:68:1 › test reloads when tracked elements change due to failed form submission
page.evaluate: Execution context was destroyed, most likely because of a navigation
88 |   await page.click("#tracked-asset-change-form button")
89 |
> 90 |   const reason = await page.evaluate(() => localStorage.getItem("reason"))
|                             ^
91 |   const unloaded = await page.evaluate(() => localStorage.getItem("unloaded"))
92 |
93 |   assert.equal(pathname(page.url()), …
```
> Tests: Resolve flaky rendering test

- src/observers/form_link_click_observer.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.ts
Closes [hotwired/turbo#820][]
Follow-up to [hotwired/turbo#461][]
[hotwired/turbo#820]: https://github.com/hotwired/turbo/issues/820
[hotwired/turbo#461]: https://github.com/hotwired/turbo/pull/461
The background
---
According to the HTML Specification's [§ 4.10.21.3 Form submission algorithm][] section, submissions transmitted as `GET` requests [mutate the `[action]` URL][mutate], overriding any search parameters already encoded into the `[action]` value:
> [Mutate action URL][algorithm]
> ---
>
> Let <var>pairs</var> be the result of converting to a list of
> name-value pairs with <var>entry list</var>.
>
> Let <var>query</var> be the result of running the
> `application/x-www-form-urlencoded` serializer with <var>pairs</var>
> and <var>encoding</var>.
>
> Set <Var>parsed action</var>'s …
> `[data-turbo-method="get"]` links: search params

- src/observers/form_submit_observer.ts
- src/observers/link_click_observer.ts
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.ts
- src/tests/helpers/page.ts
Closes [hotwired/turbo#834][]
When applications embed [Google Adsense][]-powered `<iframe>` elements, the snippets they provide render them **with** a `[name]` attribute that's set to the empty string `""`:
```html
<iframe
frameborder="0"
src="REDACTED"
id="google_ads_iframe_/REDACTED"
title="3rd party ad content"
name=""
scrolling="no"
marginwidth="0"
marginheight="0"
width="728" height="90"
data-is-safeframe="true"
sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation"
role="region"
aria-label="Advertisement"
tabindex="0"
data-google-container-id="1"
style="border: 0px; vertical-align: bottom;"
data-load-complete="true"></iframe>
```
Note the `[name=""]` in the snippet.
The guard clauses in the …
> Close Issue #834

- src/tests/fixtures/navigation.html
- src/tests/functional/rendering_tests.ts
Some tests that visit the `navigation.html` fixture exercise scroll
behavior by visiting links and other content that is below the fold. The
`style="height: 200vh"` value declared on the page's `<section>` element
is arbitrary, but double the screen size to force content below the
fold.
Unluckily, it cuts off _right_ at the beginning of the new `<iframe>`
elements in Firefox browsers, which obscures the `<a>` element and
prevents link clicks.
To resolve that issue, this commit removes the `[style]` attribute,
since the content is long enough to be scrollable.
> Fix failing Firefox test

- src/core/drive/visit.ts
- src/tests/fixtures/navigation.html
- src/tests/fixtures/rendering.html
- src/tests/fixtures/test.js
- src/tests/functional/rendering_tests.ts
- src/tests/helpers/page.ts
Closes [hotwired/turbo#794][]
Reverts the implementation change made in [hotwired/turbo#674][], and in its place passes `shouldCacheSnapshot: false` alongside `willRender: false` for the `action: "replace"` Visit proposed when following a redirect.
In order to test this behavior, this commit introduces the `readBodyMutationLogs` test utility function, along with the `window.bodyMutationLogs` property and the `BodyMutationLog` type.
`BodyMutationLog` instances are pushed onto the log `Array` whenever the `<body>` element is replaced.
[hotwired/turbo#794]: https://github.com/hotwired/turbo/issues/794
[hotwired/turbo#674]: https://github.com/hotwired/turbo/pull/674
> Skip Snapshot Caching for redirect visits

- .eslintrc
- src/tests/functional/frame_tests.ts
The `assert.equal` matcher had been overridden for some tests to allow string comparisons to act on trimmed versions of the strings. Unfortunately the overridden matcher was faulty, in that it didn't fail when the values differed. That is, `assert.equal(1, 2)` was passing rather than failing. As a result, there are a few tests that have failures that were not being reported.
This change addresses this by:
- Restoring the original `assert.equal`
- Adding a new `assert.equalIgnoringWhitespace` so we can be explicit about the cases where we want that behaviour
- Fixing a few existing test failures that had been hidden by the faulty `assert.equal`
**Note:** There are still a couple of test failures here that'll need to be fixed before this can be merged.
> Fix `assert.equal` in frame tests

- .github/workflows/ci.yml
For some reason they were disabled in https://github.com/hotwired/turbo/commit/65be4bd76eb0167f077329289ee61283cc82d124, but they were quite helpful if you wanted to test new upcoming features before they get released.
> Restore dev-builds

- .github/workflows/ci.yml
- .github/workflows/dev-builds.yml
This pull request moves the dev-builds into their own workflow so that the build doesn't fail if the dev-builds couldn't be published due to missing permissions.
Context: 
https://github.com/hotwired/turbo/pull/850/files/ec2d18bfdc97238dd3504a71d7fe689dd3d75af9#r1085421498
> Extract dev-builds to own workflow

- src/tests/functional/stream_tests.ts
- src/tests/helpers/page.ts
These tests were a bit flaky because they were asserting DOM changes that can happen asynchronously.
Changing the assertions so we wait until the change happens fixes the flakiness.
Also, introduce `waitUntilText` to wait until some text appears in the page.
> Fix flakiness in stream tests

- src/tests/functional/navigation_tests.ts
This test was consistently failing on my Mac machine.
It was because Firefox for Mac doesn't focus on links on TAB presses.
Ref. https://stackoverflow.com/a/11713537
> Fix test failure on Firefox for Mac

- src/core/errors.ts
- src/core/frames/frame_controller.ts
- src/core/frames/frame_view.ts
- src/tests/functional/frame_tests.ts
This changes the default behaviour when a frame response is missing its expected `<turbo-frame>` element.
Previously, when the response was missing its frame, we would trigger a `turbo:frame-missing` event, and then (provided that event wasn't cancelled) perform a full page visit to the requested URL.
However there are cases where the full reload makes things worse:
- If the frame contents were non-critical, reloading the page can turn a minor bug into a major one.
- It can mask some bugs where frames were intend to explicitly navigate out of the frame (`target="_top"`), by incurring a second request that loads the page that makes it seem as if it's working corrects.
- It leaves the user at a URL that may never be capable of rendering a valid response (since that URL was only intended to …
> Don't break out of frames when frame missing

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames.html
- src/tests/fixtures/frames/unvisitable.html
- src/tests/functional/frame_tests.ts
Turbo normally performs a fill page reload whenever a response contains the appropriate `turbo-visit-control` meta tag:
<meta name="turbo-visit-control" content="reload">
Such responses are considered "not visitable".
For frame requests, we have previously been ignoring any `turbo-visit-control` set in the response, and instead treating all valid frame responses as "visitable".
This commit changes this behaviour so that `turbo-visit-control` will be treated consistently for both frame and non-frame requests.
As well as being more consistent, this provides a useful escape hatch for situations where a frame request redirects to something that should be a full page reload, but which would be prevented due to that content missing the expected frame. The class example of this is when an …
> Respect `turbo-visit-control` for frame requests

- src/observers/cache_observer.ts
- src/tests/fixtures/cache_observer.html
- src/tests/functional/cache_observer_tests.ts
Renames the `[data-turbo-cache=false]` attribute (used to denote temporary elements that should be removed before caching) to `[data-turbo-temporary]` for better similarity with `[data-turbo-permanent]`, its conceptual opposite.
This is a superficial change, but worth it in terms of cohesion, I think. The pairing of "temporary" with "permanent" is just too good to ignore. Also, given the existence of `turbo-cache-*` as the namespace for _page-level_ cache control, a unique name is less likely to confuse.
References:
- https://github.com/hotwired/turbo/pull/238
> Deprecate [data-turbo-cache=false] in favor of [data-turbo-temporary]

- src/core/drive/form_submission.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
This change introduces a new optional `data-turbo-submitting-text` attribute that can be set on submit elements (inputs or buttons) in Turbo forms.
```html
<form action="/" method="post">
<input type="submit" value="Save" data-turbo-submitting-text="Saving...">
</form>
```
When the form is in a submmiting state Turbo will change the submitter content -the input value for inputs, and the innerHTML for buttons- with the `data-turbo-submitting-text`, and restore the original value when the submission ends.
This is a common requirement in many apps, to style the form submitting state and give feedback to the user that a click is already being processed.
> Allow changing the submitter text during form submission

- src/elements/stream_source_element.ts
Rollup has been printing a warning for a circular dependency in `StreamSourceElement` in the build process.
```diff
❯ yarn build
yarn run v1.22.19
$ tsc --noEmit false --declaration true --emitDeclarationOnly true --outDir dist/types && rollup -c
src/index.ts → dist/turbo.es2017-umd.js, dist/turbo.es2017-esm.js...
-(!) Circular dependency
-src/index.ts -> src/elements/index.ts -> src/elements/stream_source_element.ts -> src/index.ts
created dist/turbo.es2017-umd.js, dist/turbo.es2017-esm.js in 2.5s
✨  Done in 5.58s.
```
This pull request resolves the circular dependency by directly importing the required functions from the source file rather than the index file.
> Untangle circular dependency in `StreamSourceElement`

- src/core/view.ts
- src/http/fetch_request.ts
[**Pausing Requests**](https://turbo.hotwired.dev/handbook/drive#pausing-requests) documents `resume()` usage without requiring a value, but TypeScript disagrees.
> TS2554: Expected 1 arguments, but got 0.
Workaround is to call `resume(undefined)`, but more representative types would be better. The signature matches the `Promise` callback's `resolve` parameter here, where you'll note the `await`ed result is discarded:
https://github.com/hotwired/turbo/blob/f04a21c9418bc384f5cdafaf9d2ed21caafbf438/src/core/view.ts#L92-L95
A similar pattern is found here, where again the resolved value is discarded:
https://github.com/hotwired/turbo/blob/f04a21c9418bc384f5cdafaf9d2ed21caafbf438/src/http/fetch_request.ts#L172-L182
------------------------------------
The other option would be to remove the …
> `resume()` does not require `value`

- src/core/frames/frame_controller.ts
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.ts
Usually when submitting a form with a method other than `GET`, we clear the snapshot cache. This helps to avoid cases where we might show a stale view of some data that we just mutated.
Form submissions from inside frames were not doing this. But they ought to, for the same reason: they may have mutated some data that causes other recent pages to become stale.
To avoid this, we can clear the snapshot cache after processing a non-`GET` form, or after any failed form submission, to mirror what we do when the form is outside of any frames.
> Form submissions from frames should clear cache

- src/core/drive/form_submission.ts
- src/core/drive/navigator.ts
- src/core/frames/frame_controller.ts
- src/http/fetch_request.ts
The method name was a bit misleading, as what we're actually checking for here is whether the method is [safe][0].
We can also now make use of this method in a couple of places where we clear the snapshot cache after form submissions. The logic there is to clear the cache when performing an operation that is unsafe.
[0]: https://developer.mozilla.org/en-US/docs/Glossary/Safe/HTTP
> Rename `isIdempotent` to `isSafe`

- src/polyfills/submit-event.ts
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.ts
This PR addresses an issue where the current polyfill for SubmitEvent is not functioning as expected on the newer versions of Safari. It appears that the original webkit issue the polyfill was meant to address has been resolved, and the polyfill is now introducing undesired behavior.
Specifically, this issue is observed when invoking the requestSubmit() method with a submitter as an argument in Safari 16.5. According to the current behavior, the submitter argument seems to be ignored (ref https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit).
In an attempt to correct this, I've made adjustments to the polyfill logic and added a browser test to confirm the fix. The test fails when executed in the webkit environment with the old polyfill but passes successfully …
> Fix for SubmitEvent polyfill breaking requestSubmit() for newer Safari versions

- src/core/drive/page_snapshot.ts
- src/core/drive/page_view.ts
- src/core/drive/view_transitions.ts
- src/tests/fixtures/transitions/left.html
- src/tests/fixtures/transitions/other.html
- src/tests/fixtures/transitions/right.html
- src/tests/functional/drive_view_transition_tests.ts
Adds the ability to use the [View Transition API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API). It's based around the MPA View Transition support which is currently becoming available in Chrome.
When navigating between pages, we check for the presence of `view-transition` meta tags in both documents, with a value of `same-origin`. If those tags are present, and the browser supports the View Transition API, we can render the page update within a transition.
When not opted in with the meta tags, or when support is not available, we fallback to the previous behaviour.
This mimics the behaviour that a supporting browser would have when performing a full-page navigation between those pages.
We also suppress snapshot caching on pages that specify these meta tags, since …
> Support View Transition API for navigations

- rollup.config.js
So that build tools like esbuild or rollup-plugin-license can detect the banner and keep the license in the minified output.
The banner is only a few bytes, so bundle size is not a concern.
Ref. https://github.com/evanw/esbuild/issues/2745
> Add ! to the copyright banner comment

- src/tests/functional/form_submission_tests.ts
[Coverage for 954][]
Assert that `[aria-busy="true"]` at the start of a `GET` request
initiated by a `<form>` element and handled as a page-wide navigation by
Turbo Drive.
[Coverage for 954]: https://github.com/hotwired/turbo/issues/954
> Add test coverage toggling `[aria-busy]` for `GET` Form Submissions

- src/core/frames/frame_controller.ts
- src/core/session.ts
- src/core/view.ts
- src/tests/functional/rendering_tests.ts
Passes the renderer's `isPreview` attribute into the event detail on `'turbo:before-render'` and `'turbo:render'` events.
`isPreview` signifies whether the content currently being rendered is from the turbo cache or not, and this bit of information is very useful for any listeners that might want to act on those two events differently for cached or non-cached content.
Eg, the following listeners:
```ruby
document.addEventListener("turbo:before-render", (event) => {
console.log("turbo:before-render")
console.log(event.detail)
})
document.addEventListener("turbo:render", (event) => {
console.log("turbo:render")
console.log(event.detail)
})
```
now produce these event details (when navigating to a page that has a cache entry, both events fire twice):
So it's now possible to do things like... …
> Proposal: pass isPreview value into the event detail in render events

- src/core/drive/preloader.ts
This PR renames header and value for preloaded requests to `x-purpose: preview`. See discussion in #924.
> Rename header for preload requests

- src/core/drive/visit.ts
- src/tests/functional/rendering_tests.ts
I'm not 100% sure if this is the correct approach, but as far as I can tell, this just dispatches the `turbo:load` event after rendering a 404.
Fixes https://github.com/hotwired/turbo/issues/958
> Dispatch turbo:load after loading 404 response

- playwright.config.js
- web-test-runner.config.mjs
**Description**
This PR introduces a couple of important updates to our project's configuration files to address specific issues and improve the reliability of our testing and browser automation setup.
This commit addresses issues related to timeouts and target closures in our test framework. It includes improvements to handle timeouts more effectively and prevent unexpected target closures during test execution.
- Playwright browser contexts now have increased timeout settings.
- Web Test Runner configuration has been adjusted to handle timeouts gracefully.
This commit ensures the reliability and stability of our automated tests. Running `yarn test` now perfectly process `test:unit && yarn test:browser` effectively and proceeds to playwright test without any hassle.
**Reason for …
> fix: Resolve issues with timeouts and target closures in test framework

- src/elements/stream_source_element.js
- src/tests/functional/stream_tests.js
Closes [hotwired/turbo#969][]
When a `<turbo-stream-source>` element is removed, close the connection that is created during connection.
[hotwired/turbo#969]: https://github.com/hotwired/turbo/issues/969
> Close `StreamSource` when `<turbo-stream-source>` disconnects

- src/core/frames/frame_controller.js
- src/tests/fixtures/frame_preloading.html
- src/tests/fixtures/frames/body_script.html
- src/tests/fixtures/frames/body_script_2.html
- src/tests/fixtures/frames/eval_false_script.html
- src/tests/fixtures/frames/form-redirect.html
- src/tests/fixtures/frames/form-redirected.html
- src/tests/fixtures/frames/form.html
- src/tests/fixtures/frames/frame.html
- src/tests/fixtures/frames/frame_for_eager.html
- src/tests/fixtures/frames/hello.html
- src/tests/fixtures/frames/part.html
- src/tests/fixtures/frames/preloading.html
- src/tests/fixtures/frames/recursive.html
- src/tests/fixtures/frames/self.html
- src/tests/fixtures/frames/unvisitable.html
- src/tests/fixtures/frames/without_layout.html
- src/tests/fixtures/rendering.html
- src/tests/fixtures/tabs.html
- src/tests/fixtures/tabs/three.html
- src/tests/fixtures/tabs/two.html
- src/tests/functional/rendering_tests.js
After the changes made in [@hotwired/turbo#867][] and changes made in [@hotwired/turbo-rails#428][] (the canonical server-side implementation), Turbo expects full HTML documents in response to requests with `Turbo-Frame:` headers.
Prior to this commit, the `FrameController` compensated for missing pieces of an HTML document by taking an HTML "snapshot" of the current page through the `<html>` element's [outerHTML][].
This commit changes the `fetchResponseLoaded` callback to read the `responseHTML` directly from the `FetchResponse`, since that will be a fully formed HTML document in Turbo v7.3.0 and later.
To support that change, this commit also updates various `src/test/fixtures` files to render fully-formed HTML documents.
[@hotwired/turbo#867]: …
> Create Frame Snapshot from Fetch Response HTML

- src/tests/functional/navigation_tests.js
In this commit, I've enhanced the stability of various navigation test cases by ensuring that asynchronous click actions are correctly awaited with 'await page.click()' for the following scenarios:
- Same-origin unannotated link test
- Drive enabled: Click an element in the shadow DOM wrapped by a link in the light DOM
- Drive disabled: Click an element in the shadow DOM within data-turbo='false'
- Drive enabled: Click an element in the slot
- Drive disabled: Click an element in the slot within data-turbo='false'
- Drive disabled: Click an element in the nested slot within data-turbo='false'
- Following a same-origin unannotated link with search params
- Following a same-origin unannotated form with method=GET
- Following a same-origin data-turbo-action=replace link
- Following a …
> fix: Improve test stability in navigation test cases

- src/core/drive/form_submission.js
- src/http/fetch_request.js
- src/tests/functional/form_submission_tests.js
- src/tests/functional/navigation_tests.js
- src/tests/functional/rendering_tests.js
- src/tests/functional/visit_tests.js
The problem
---
Prior to this commit, instances of `FormSubmission` and `FetchRequest`
referenced in dispatched `turbo:submit-start` and
`turbo:before-fetch-request` events were tedious to modify from a host
application.
For example, the `FormSubmission` instance made available through
`event.detail.formSubmission` exposed properties that _seemed_ writable.
Unfortunately, any mutations to `formSubmission.method` or
`formSubmission.location` from within host application event listeners
(like `turbo:before-fetch-request`) occur _after_ the underlying 
`FetchRequest` instance is built, which has subtle and not obvious 
implications. In practice, modifications to these properties are 
unobserved by the underlying `FetchRequest` instance, and have no effect
on the ensuing `fetch` call. …
> Override `FetchOptions` from event listeners

- src/observers/form_link_click_observer.js
- src/tests/functional/frame_tests.js
This PR addresses a specific issue that arises when using a Turbo Stream link within a Turbo Frame in a Rails 7 application. Clicking on such a link currently sets the `src` attribute of the Turbo Frame element. Although Turbo saves this state for browser history navigation, it fails to fetch the content correctly. This is because the `src` attribute is intended to be used for Turbo Stream responses, leading to unexpected behavior.
1. Create a new Rails 7 application.
2. Add a Turbo Stream link inside a Turbo Frame.
3. Click the Turbo Stream link.
4. Observe that the `src` attribute of the Turbo Frame element is set.
5. Navigate the browser history.
6. Turbo fails to fetch the content.
This PR adds a conditional check for the `data-turbo-stream` attribute. If the attribute exists, the …
> FIX: Turbo stream link setting the src of a turbo frame container

- src/core/renderer.js
- src/core/snapshot.js
- src/core/streams/stream_message_renderer.js
- src/tests/fixtures/stream.html
- src/tests/functional/autofocus_tests.js
- src/tests/functional/stream_tests.js
- src/util.js
When a `<turbo-stream>` modifies the document, it has the potential to
affect which element has focus.
For example, consider an element with an `[id]` that has focus:
```html
<label for="an-input">
<input id="an-input" value="an invalid value"> 
```
Next, consider a `<turbo-stream>` element to replace it:
```html
<turbo-stream action="replace" target="an-input">
<template>
<input id="an-input" value="an invalid value" class="invalid-input">
</template>
</turbo-stream>
```
Prior to this commit, rendering that `<turbo-stream>` would remove the
element with focus, and never restore it.
After this commit, the `Session` will capture the `[id]` value of the
element with focus (if there is any), then "restore" focus to an element
in the document with a matching `[id]` attribute _after_ the …
> Turbo Streams: Manage element focus

- src/tests/functional/drive_tests.js
In the `drive_tests.js` file, I improved test stability by introducing steps in two test cases: "test drive to external link" and "test drive enabled by default; click link inside data-turbo='false'."
The added  calls ensure that the respective elements (e.g., `#drive_enabled_external` and `#drive_disabled`) are present and visible before interacting with them, reducing the chances of element unavailability issues during test execution.
This resolves test failures where elements were not immediately accessible, leading to test timeouts.
> fix: Enhance test stability in drive_tests.js

- .github/workflows/ci.yml
This adds an [upload artifact](https://github.com/actions/upload-artifact) Github action step to store the results of the build in the Github Actions workflow.
This allows us to download the artifacts from the Github Actions UI. Sometimes it's useful to have the artifacts available for debugging purposes, or to test a branch in an application before merging.
> Upload dist artifacts to GitHub Actions

- src/core/cache.js
- src/core/drive/cache_stores/disk_store.js
- src/core/drive/cache_stores/memory_store.js
- src/core/drive/page_snapshot.js
- src/core/drive/page_view.js
- src/core/drive/preloader.js
- src/core/drive/snapshot_cache.js
- src/core/drive/visit.js
- src/tests/fixtures/disk_cache.html
- src/tests/functional/disk_cache_tests.js
- src/tests/functional/preloader_tests.js
This commit extends the Turbo cache API to allow for the use of different cache stores. The default store is still the in-memory store, but a new persistent cache store is now available.
The disk store uses the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) to store and retrieve snapshots from the browser's cache. This allows for the snapshots to be persisted across different tabs, page reloads and even browser restarts.
The disk store is not enabled by default. To enable it, you need to set the `Turbo.cache.store` property to `"disk"`.
```js
Turbo.cache.store = "disk"
```
This is also a stepping stone to implement offline support with Service Workers. With a Service Worker in place, and the disk cache store enabled, we can still serve cached snapshots even …
> Add disk cache store

- src/core/drive/visit.js
- src/core/native/browser_adapter.js
- src/tests/functional/navigation_tests.js
This commit fixes a bug where navigating back after submitting a POST form would not show the previous page. The bug was introduced in https://github.com/hotwired/turbo/pull/949. The new cache API is async since it needs to access `CacheStorage` which is async. In that PR, `getCachedSnapshot` was changed to be async, but `hasCachedSnapshot` was not changed. This meant that `getCachedSnapshot` would always return a promise, which is truthy, and so `hasCachedSnapshot` which just checked that the return value was not null would always return true.
The bug would show up when you tried to navigate back to a page after a post form submission. The form submission would clear the cache, but the restoration visit would think it had a cached snapshot and so would not issue a request. This meant …
> Fix back navigation after POST form submission

- src/core/drive/page_renderer.js
- src/core/drive/page_snapshot.js
- src/tests/fixtures/es_locale.html
- src/tests/fixtures/rendering.html
- src/tests/functional/rendering_tests.js
Closes [#967][]
Change the `<html>` element's `[lang]` attribute during navigation. Currently, this isn't possible from applications (without a lot of trouble), since the [turbo:before-render][] event is scoped to the `newBody`.
In order to support this behavior, change the `PageSnapshot` constructor to accept an instance of [HTMLHtmlElement][] (the `<html>` element) so that that element can be accessible from the `PageRenderer`.
[#967]: https://github.com/hotwired/turbo/issues/967
[turbo:before-render]: https://turbo.hotwired.dev/reference/events
[HTMLHtmlElement]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLHtmlElement
> Set `html[lang]` during navigation

- src/core/cache.js
- src/core/index.js
- src/core/session.js
When the `Cache` class was [introduced in a54ac17][], it depended on a `Session` instance. When it was [modified in f86a376][], that dependency was no longer necessary.
This commit preserves the export of the `Turbo.cache` property while re-arranging the location it's declared. Instead of instantiating the `Cache` instance in `@hotwired/turbo/core/`, this commit defines it as a property on the `Session` instance.
[introduced in a54ac17]: https://github.com/hotwired/turbo/commit/a54ac176a707487feee0424b8d719927305c8b7a
[modified in f86a376]: https://github.com/hotwired/turbo/commit/f86a376b0d088c8ff83ef8180b95d492527902e5
> Move `Cache` instantiation to `Session`

- src/tests/fixtures/form.html
- src/tests/fixtures/frames/form.html
- src/tests/functional/form_submission_tests.js
Closes [#901][]
Add test coverage for submitting `<form>` elements with `[data-turbo-frame="_top"]`. Coverage includes both `<form>` elements outside of `<turbo-frame>` *and* `<form>` elements that are descendants of `<turbo-frame>` elements.
[#901]: https://github.com/hotwired/turbo/issues/901
> Add test coverage for submitting `form[data-turbo-frame="_top"]`

- src/tests/unit/export_tests.js
According to the [official documentation][], applications that need to extend `StreamActions` should be importing it directly from the module instead of accessing it through `window.Turbo.StreamActions`.
This commit adds test coverage to exercise the corresponding `import`. It also re-arranges the `export` to explicitly occur in the `@hotwired/turbo` module itself, instead of being transitively exported as part of the `@hotwired/turbo/core` module.
[official documentation]: https://turbo.hotwired.dev/handbook/streams#custom-actions
> Add test coverage for `StreamActions` export

- src/core/index.js
- src/index.js
Resolves https://github.com/hotwired/turbo/pull/1026#issuecomment-1782605125
> Remove Circular Build Dependency

- src/core/drive/navigator.js
- src/core/native/browser_adapter.js
- src/tests/unit/native_adapter_support_tests.js
This fixes a bug introduced in: https://github.com/hotwired/turbo/pull/410
#410 made a change that made the decision to visit internal vs external urls outside of the `adapter`. This works fine in the browser context, but breaks the expectations for the `turbo-ios` and `turbo-android` native adapters.
Native apps using the native turbo libraries already must provide logic for properly routing internal/external urls to the WebView or an external app/browser. This change brings back the capability for programmatic `Turbo.visit(url)` proposals to flow through the adapter, even for external urls. This gives the native adapters the opportunity to pass external url visit proposals to the native apps.
Before this change `Turbo.visit("https://google.com")` would result in the native app's Turbo …
> Always go through the adapter to decide how to propose visits

- src/tests/functional/async_script_tests.js
- src/tests/functional/autofocus_tests.js
- src/tests/functional/cache_observer_tests.js
- src/tests/functional/drive_disabled_tests.js
- src/tests/functional/drive_tests.js
- src/tests/functional/form_mode_tests.js
- src/tests/functional/form_submission_tests.js
- src/tests/functional/frame_navigation_tests.js
- src/tests/functional/frame_tests.js
- src/tests/functional/import_tests.js
- src/tests/functional/loading_tests.js
- src/tests/functional/navigation_tests.js
- src/tests/functional/pausable_rendering_tests.js
- src/tests/functional/pausable_requests_tests.js
- src/tests/functional/preloader_tests.js
- src/tests/functional/rendering_tests.js
- src/tests/functional/scroll_restoration_tests.js
- src/tests/functional/stream_tests.js
- src/tests/functional/visit_tests.js
- src/tests/unit/deprecated_adapter_support_tests.js
- src/tests/unit/export_tests.js
- src/tests/unit/stream_element_tests.js
The fact that each test case description starts with `"test"` is an artifact of the pre-Playwright test suite. Prior to Playwright, test cases were inferred from function names that started with `"test"`.
Since Playwright doesn't impose those same expectations, the prefix can be omitted.
> Tests: remove `"test"` docstring prefix

- src/core/drive/navigator.js
- src/core/drive/visit.js
- src/tests/unit/deprecated_adapter_support_tests.js
- src/tests/unit/native_adapter_support_tests.js
This fixes a problem introduced when the cache interface changed in https://github.com/hotwired/turbo/pull/949
Since the cache can be loaded from disk using the browser Cache API, it is possible that the cache snapshot will be loaded asynchronously. This means that the calls to load cache snapshots need to be awaited.
Because of that we also changed `visit.hasCachedSnapshot()` to be async and return a `Promise`. However, [hasCachedSnapshot is used in the iOS adapter](https://github.com/hotwired/turbo-ios/blob/c476bac66f260adbfe930ed9a151e7637973ff99/Source/WebView/turbo.js#L119) and serialized into and data object we send to the native side via `postMessage`. When `postMessage` receives a Promise instead of a boolean value it fails with a `DataCloneError` because it can't serialize the …
> Move cache snapshot loading to Visit#start()

- src/core/drive/navigator.js
- src/core/drive/page_view.js
- src/tests/fixtures/page_refresh.html
- src/tests/functional/page_refresh_tests.js
Turbo will render 422 responses to allow handling form errors. A common scenario in Rails is to render those setting the satus like:
```ruby
render "edit", status: :unprocessable_entity
```
This change will consider such operations a "page refresh" and will also consider the scroll directive.
Thanks to @seanpdoyle for the heads up here.
> Respect morphing and scroll preservation settings when handling form errors

- src/core/cache.js
- src/core/session.js
- src/tests/unit/export_tests.js
We refactored the cache class to not take a session in the constructor in 485115d24a3b331e6fc2a0e2f564bde7dd063309.
But after reverting the disk cache https://github.com/hotwired/turbo/pull/1062 the cache needs a reference to the session again.
> Pass session instance to cache constructor

- src/tests/functional/page_refresh_tests.js
Idiomorph will preserve focus, but discard content. Version [0.0.9][] introduces the `ignoredActiveValue:` option to preserve the value for the element with focus. Since the currently packaged build isn't caught up to that version, the `[data-turbo-permanent]` treatment enables a similar kind of behavior.
This commit adds test coverage to ensure that focus preservation is global, and value preservation requires opt-in with `[data-turbo-permanent]`.
[0.0.9]: https://github.com/bigskysoftware/idiomorph/tree/v0.0.9#options
> Add coverage for focus and value preservation during morph

- src/core/drive/morph_renderer.js
- src/tests/fixtures/frame_refresh_morph.html
- src/tests/fixtures/frame_refresh_reload.html
- src/tests/fixtures/page_refresh.html
- src/tests/fixtures/page_refresh_replace.html
- src/tests/functional/page_refresh_tests.js
This adds a new turbo-frame attribute: `refresh`. When its value is `morph`:
* It will reload the turbo frame with morphing during a page refresh.
* It won't update the turbo frame with the server response.
* It won't remove it if it's missing in the server response.
An example where these frames are useful are for pagination, or for other scenarios where you load new state in the screen that you want to preserve during page refreshes, but that you also want to reload because the user action might have affected them.
This attribute was part of [the original proposal we presented in Rails World](https://www.youtube.com/watch?v=m97UsXa6HFg), then [we removed it](https://github.com/hotwired/turbo/pull/1019/commits/0c6a95d07fd7661e734ed1fbfe19daa9a00b3fd4), because we thought it wasn't …
> Restore attribute "refresh=morph" to flag turbo frames to reload during a page refresh

- src/core/native/browser_adapter.js
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.js
- src/tests/server.mjs
Closes [#962][]
Prior to this commit, the progress bar is hidden between the Turbo Drive visits' `turbo:before-fetch-response` event and the `turbo:render` event.
This commit changes that behavior to hide the bar when the Visit is complete (some time prior to the `turbo:load` event).
[#962]: https://github.com/hotwired/turbo/issues/962
> Hide Progress bar on `turbo:load`

- src/core/drive/navigator.js
- src/core/drive/page_view.js
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.js
This changes the default action for form submission that redirect to the current location from "advance" to "replace". This makes more sense since we're re-rendering the current page, there should be no new entry in the history.
We are also changing the morphing behaviour to only kick in when the visit action is "replace". This is to avoid morphing the page when, for example, we are following a link, unless we opt in to morphing by setting the data-turbo-action attribute to replace.
The main use case for morphing remains the same: you submit a form that changes some state and redirect to the same location. Turbo handles the redirect and morphs the page to reflect the new state.
> Change default action for form submissions that redirect to the current location

- src/http/fetch.js
- src/tests/unit/export_tests.js
Closes [@hotwired/turbo-rails#526][]
Prevent naming collisions between the new `Turbo.fetch` function and the built-in `window.fetch` function.
To do so, create a module-local reference to `window.fetch`, and define the exported function as `fetchWithTurboHeaders`. At export-time, rename to `fetch` so that consumers can continue to import it as `Turbo.fetch`.
[@hotwired/turbo-rails#526]: https://github.com/hotwired/turbo-rails/issues/526
> Avoid infinite recursion from `window.fetch` name collision

- package.json
The library is bundled within Turbo so there's no need for apps using Turbo to install it.
> Include idiomorph as a dev dependency

- src/core/index.js
- src/core/streams/stream_actions.js
- src/index.js
Follow-up to [#1049][]
Follow-up to [#1073][]
Related to [#1078][]
Replace an internal `window.Turbo.session` access with an `import { session }` statement.
Prior attempts at this change introduced circular dependencies. This attempt does not. Additionally, this change maintains the ability for consumers to access StreamActions through `window.Turbo.StreamActions`, while also enabling `import { StreamActions } from "@hotwired/turbo"` (or `from "@hotwired/turbo-rails"`).
[#1049]: https://github.com/hotwired/turbo/pull/1049
[#1073]: https://github.com/hotwired/turbo/pull/1073
[#1078]: https://github.com/hotwired/turbo/pull/1078
> Import `session` instead of reading `window.Turbo.session`

- src/core/drive/page_view.js
- src/core/drive/visit.js
- src/tests/fixtures/page_refresh.html
- src/tests/functional/page_refresh_tests.js
The current logic was triggering on any navigation operation, not only on page refreshes.
Fixes https://github.com/hotwired/turbo/issues/1081
> Don't preserve scroll position unless it's a page refresh

- src/core/drive/page_view.js
- src/tests/fixtures/page_refresh.html
- src/tests/functional/page_refresh_tests.js
Before this commit, URLs had to be exactly the same for the possibility of a refresh with morphing.
Now, it only checks that the paths are equal, regardless of whether they have different search params.
From my perspective, search params don't determine whether it is a refresh or not. The most representative example that comes to mind is the same case as a Rails controller. A show action could have different search params, but in essence, it remains the same action and the same page.
Additionally, sometimes when clicking a link on social media, for example, tracking parameters are injected. If these parameters exist and a form is submitted, Turbo would not detect that it is a refresh.
These are just small examples of use cases, but obviously there are many more.
> Page refreshes: Use pathname instead of href to detect if locations are equal

- src/core/drive/visit.js
- src/core/frames/frame_renderer.js
- src/core/streams/stream_message_renderer.js
In #1042, `nextRepaint` util was created, which only calls `nextAnimationFrame` when the page is in the foreground, and when it is in the background it calls `nextEventLoopTick`. Then, `nextAnimationFrame` was replaced in the `StreamElement` `render` method to allow Turbo streams actions to run even if the page is in the background.
Now that a page refresh can also be triggered by Turbo streams, it is necessary to change the remaining calls to `nextAnimationFrame`, so that page refreshes and Turbo frame reloads can occur in the background as well.
So, this change ensures that page refreshes work properly when the page is in the background.
> Page refreshes: Replace remaining calls to nextAnimationFrame by nextRepaint

- src/core/drive/preloader.js
- src/core/session.js
- src/tests/fixtures/frame_preloading.html
- src/tests/fixtures/frames/preloading.html
- src/tests/fixtures/preloading.html
- src/tests/functional/preloader_tests.js
- src/tests/server.mjs
Closes [#857](https://github.com/hotwired/turbo/issues/857)
Prior to this change, _any_ `<a>` element with `[data-turbo-preload]` would be preloaded. With that behavior comes some risk:
* if an element is nested within a `[data-turbo="false"]` element, the preloading would occur unnecessarily
* if an element has `[data-turbo-stream]`, the preloaded request won't be the same as the ensuing request due to differences in the `Accept:` header
* if an element has `[data-turbo-method]`, the preloaded request won't be the same as the ensuing request due to differences in the method
* if an element is within a `<turbo-frame>` or driving a frame via `[data-turbo-frame]`, the preloaded request won't be the same as the ensuing request due to differences in the `Turbo-Frame:` header
This commit …
> Guard `[data-turbo-preload]` with conditionals

- src/core/drive/preloader.js
- src/tests/fixtures/hot_preloading.html
- src/tests/fixtures/preloaded.html
- src/tests/fixtures/preloading.html
- src/tests/functional/preloader_tests.js
Closes [#963][]
Replace the raw call to `fetch` with a new `FetchRequest` instance that treats the `Preloaded` instances as its delegate. During that request's lifecycle, dispatch the `turbo:before-fetch-request` and `turbo:before-fetch-response` events with the `<a>` element as its target.
Prepare the request with the [Sec-Purpose][] header in the `prepareRequest` delegate callback.
Write to the snapshot cache from within the
`requestSucceededWithResponse` delegate callback.
[#963]: https://github.com/hotwired/turbo/issues/963
[Sec-Purpose]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Purpose#prefetch
> Dispatch `turbo:before-fetch-{request,response}` during preloading

- src/core/drive/form_submission.js
- src/tests/fixtures/form.html
- src/tests/functional/form_submission_tests.js
This is useful for styling the form while it is submitting.
Before this change, we were only setting aria-busy on frames while they were loading and on the html element while Turbo was processing a visit.
> Set aria-busy on the form element during a form submission

- src/core/session.js
- src/tests/functional/page_refresh_stream_action_tests.js
- src/tests/helpers/page.js
- src/tests/unit/stream_element_tests.js
- src/util.js
> Debounce page refreshes triggered via Turbo streams

- src/core/drive/page_renderer.js
- src/core/drive/progress_bar.js
- src/tests/fixtures/additional_script.html
- src/tests/fixtures/rendering.html
- src/tests/fixtures/stylesheets/common.css
- src/tests/fixtures/stylesheets/left.css
- src/tests/fixtures/stylesheets/left.html
- src/tests/fixtures/stylesheets/right.css
- src/tests/fixtures/stylesheets/right.html
- src/tests/functional/drive_stylesheet_merging_tests.js
- src/tests/functional/rendering_tests.js
- src/tests/helpers/page.js
When navigating to another page, Turbo merges the `<head>` contents from the current and new pages, which results in a `<head>` containing the superset of both.
For certain items, like scripts, this makes sense. We have no way to remove a running script. But that's not the case for styles: styles can be unloaded easily, and for the page to display properly, we need to do so. Otherwise styles kept in scope from a previous page could cause a page to render incorrectly.
The common way to avoid this has been to use `data-turbo-track="reload"` to force a reload if styles change. This works, but it's a bit heavy-handed, causing full page reloads that could have been avoided.
There are a couple of common cases where updating styles on the fly would be useful:
- Deploying a CSS change. Clients …
> Remove unused stylesheets when navigating

- src/core/drive/page_renderer.js
- src/core/drive/progress_bar.js
- src/tests/functional/drive_stylesheet_merging_tests.js
After https://github.com/hotwired/turbo/pull/1128 we are dynamically removing styles we're no longer using on page navigations. Unfortunately, Trix dynamically adds some styles to the head that we need to keep around. Otherwise, the editor will not render correctly after a page change.
We can detect those styles because Trix also adds a `data-tag-name` attribute to the style elements it adds.
Ideally, we would move those styles to Trix's CSS file, but for now we'll just skip removing them. We don't want to force everyone upgrading to Turbo v8 to also upgrade Trix.
Ref:
- https://github.com/basecamp/trix/blob/06d8b1db5fb682d007c5ca041884f6297674c8b7/src/trix/elements/trix_editor_element.js#L108-L162
- https://github.com/basecamp/trix/blob/06d8b1db5fb682d007c5ca041884f6297674c8b7/src/trix/co …
> Keep Trix dynamic styles in the head

- src/core/frames/frame_controller.js
- src/core/session.js
- src/core/view.js
- src/tests/functional/rendering_tests.js
It is not necessary to pass along isPreview through various methods in order to determine whether a render is a preview since that can be determined via the data-turbo-preview attribute. (As discussed in https://github.com/hotwired/turbo/pull/926#issuecomment-1692292545)
> Revert: Proposal: pass isPreview value into the event detail in render events (#926)

- src/observers/link_prefetch_observer.js
- src/tests/fixtures/hover_to_prefetch.html
- src/tests/functional/link_prefetch_observer_tests.js
With Instaclick enabled and given an HTML structure like this:
```html
<turbo-frame id="frame" target="_top">
<a href="/src/tests/fixtures/prefetched.html">Hover to prefetch me</a>
</turbo-frame>
```
When the user hovers over the link, the turbo-frame header should not be sent in the prefetch request because the wrapping turbo-frame has a target of `_top`.
If we don't respect this turbo-rails sees the turbo-frame header and renders a turbo-frame response with a minimal layout that doesn't include any assets in the head. When turbo processes the response it may find a missmatch in tracked assets and cause a reload.
//cc @davidalejandroaguilar
> Ensure that the turbo-frame header is not sent when the turbo-frame has a target of _top

- src/core/drive/page_renderer.js
- src/core/drive/progress_bar.js
- src/tests/fixtures/stylesheets/left.html
- src/tests/fixtures/stylesheets/right.html
- src/tests/functional/drive_stylesheet_merging_tests.js
To track stylesheets and styles that we can dynamically remove when navigating.
We introduced this behaviour in https://github.com/hotwired/turbo/pull/1128 and thought it would be a good default to avoid full page reloads when styles change.
However, it seems it's quite common for libraries to add stylesheets and styles to the head that they want to keep around. For example, see
- https://github.com/hotwired/turbo/pull/1133
- https://github.com/hotwired/turbo/issues/1139
So let's make this behaviour opt-in by adding a `data-turbo-track="dynamic"` attribute to stylesheets and styles that we want to dynamically remove when they are no longer in a new page after a navigation.
This avoids any breaking changes for existing apps.
> Introduce data-turbo-track="dynamic"

- src/core/drive/morph_renderer.js
- src/core/view.js
- src/tests/fixtures/page_refresh.html
- src/tests/fixtures/test.js
- src/tests/functional/page_refresh_tests.js
- src/tests/functional/rendering_tests.js
Follow-up to [9944490][]
Related to [#1083]
Related to [@hotwired/turbo-rails#533][]
The problem
---
Some client-side plugins are losing their state when elements are
morphed.
Without resorting to `MutationObserver` instances to determine when a
node is morphed, uses of those plugins don't have the ability to prevent
(without `[data-turbo-permanent]`) or respond to the morphing.
The proposal
---
This commit introduces a `turbo:before-morph-element` event that'll
dispatch as part of the Idiomorph `beforeNodeMorphed` callback. It'll
give interested parties access to the nodes before and after a morph. If
that event is cancelled via `event.preventDefault()`, it'll skip the
morph as if the element were marked with `[data-turbo-permanent]`.
Along with `turbo:before-morph-element`, this commit …
> Introduce `turbo:{before-,}morph-{element,attribute}` events

- package.json
- src/core/drive/morph_renderer.js
- src/tests/fixtures/page_refresh.html
- src/tests/functional/page_refresh_tests.js
- yarn.lock
Morph with the [ignoreActiveValue: true][] option to morph the currently focused element's attributes, but preserve its value.
This behavior can be extremely helpful when paired with an auto-submitting `<form>` element, like a typeahead `[role="combobox"]`, or an auto-submitting [`<input type="search">`][search].
This commit depends on a fork of `idiomorph` that [fixes a bug related to `ignoreActiveValue: true`][bigskysoftware/idiomorph#34].
https://github.com/hotwired/turbo/assets/2575027/ca40524f-da6c-40fd-aacf-1bbe74be72f5
[ignoreActiveValue: true]: https://github.com/bigskysoftware/idiomorph#options
[search]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search
[bigskysoftware/idiomorph#34]: https://github.com/bigskysoftware/idiomorph/pull/34
> Morph with `ignoreActiveValue: true`

- src/core/drive/morph_renderer.js
- src/tests/fixtures/page_refresh.html
- src/tests/functional/page_refresh_tests.js
Fixes https://github.com/hotwired/turbo/issues/1105
Fixes https://github.com/hotwired/turbo/issues/1116
> Ensure page refreshes cause a reload when assets change

- src/observers/link_prefetch_observer.js
First, import the `StreamMessage` module to utilize the `contentType`
instead of the hard-coded `"text/vnd.turbo-stream.html"` String.
Next, replace occurrences of [HTMLElement.dataset][] with the
`"data-"`-prefixed calls to [Element.getAttribute][] so that they are as
`grep`-able as their counterparts elsewhere in the codebase.
Finally, remove a `link` comparison conditional clause, since it's
repeated verbatim several lines prior to it.
[HTMLElement.dataset]: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset
[Element.getAttribute]: https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute
> `LinkPrefetchObserver`: replace `dataset` with `getAttribute`

- src/core/drive/visit.js
- src/tests/fixtures/one.html
- src/tests/fixtures/page_refresh.html
- src/tests/functional/page_refresh_tests.js
Fixes #1080
In #1080, when rendering the cached snapshot as preview, idiomorph is causing `document.body` to become `null`, I didn't quite understand why.
Anyway, In my opinion morphing should not render previews anyway. If the goal of morphing is to maintain state, why would we want to do that and show a previous version of the document for a moment?
So, this PR does just that. If it is a page refresh, the cached snapshot will not be rendered as preview.
> Page refreshes: Don't render previews

- src/core/frames/frame_controller.js
- src/core/session.js
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.js
Closes [#489][]
Closes [#468][]
First, add test coverage to exercise the `<turbo-frame id="frame">` and
`<turbo-frame id="hello" target="frame">` as outlined in a
[comment on #489][].
Next, add coverage to support driving a `<turbo-frame
data-turbo-action="advance">` through the `Turbo.visit` method. To pass
that test coverage, invoke
`frameElement.delegate.proposeVisitIfNavigatedWithAction(frameElement)`
prior to modifying the element's `[src]` attribute.
To support the implementation changes necessary to pass the tests, this
commit changes the `proposeVisitIfNavigatedWithAction(frame, action)`
interface by flattening the variable arguments into a single `action`
argument, then moving the `getVisitAction` call to the call sites that
require it. The call sites that know their `action` …
> Drive `turbo-frame` with `Turbo.visit(url, { frame:, action: })`

- src/observers/link_prefetch_observer.js
- src/tests/functional/link_prefetch_observer_tests.js
While testing https://github.com/hotwired/turbo/pull/1147 I found an issue on touch devices that often leads to duplicated requests on mobile. The culprit seems a `mouseenter` event that Safari fires after a `touchend` for compatibility reasons. The `mouseenter` was overriding the current prefetch request launched on `touchstart` causing a second one to be triggered.
According to ChatGPT:
> Some browsers may synthesize mouse events (including `mouseenter`) after touch events to ensure compatibility with web content not designed for touch interfaces. This means that a `mouseenter `event might be fired on a touch device, usually after a `touchend` event, as part of the sequence to simulate mouse interaction. This behavior can vary between browsers and might not always be consistent.
Seems …
> Disable InstantClick for touch events

- src/observers/link_prefetch_observer.js
- src/tests/fixtures/hover_to_prefetch.html
- src/tests/functional/link_prefetch_observer_tests.js
This PR adds some more conditions where a link is not considered safe to be prefetched.
The risk/reward ratio favors a more conservative approach. If we don't prefetch a link the interaction can be a bit slower, but if we prefetch a link that is not safe, we may trigger a bug.
The conditions are quite specific, in any case, so they shouldn't trigger often.
The new conditions are:
- If the link is a UJS link (i.e. it has a `data-remote` attribute).
- If the link has a data-turbo-confirm attribute.
- If the link has a data-turbo-stream attribute.
The PR also cleans up the code a bit, extracting each of the conditions into helper methods.
Fixes https://github.com/hotwired/turbo/issues/1170
Fixes https://github.com/hotwired/turbo/issues/1174
> Add more prefetch conditions

- src/core/frames/frame_controller.js
- src/elements/frame_element.js
- src/tests/fixtures/frame_refresh_after_navigation.html
- src/tests/fixtures/page_refresh.html
- src/tests/functional/loading_tests.js
- src/tests/functional/page_refresh_tests.js
I encountered the following problem : 
consider a turbo frame like so on index.html
```html
<turbo-frame id="foobar">
<a href="/some/path">Click me</a>
</turbo-frame>
```
When the link is clicked, the HTML will look like this
```html
<turbo-frame id="foobar" src="/some/path" complete>
Some content
</turbo-frame>
```
If the page is then refreshed with morphing, my expectation was that everything will return to the initial state.
However, in practice, the frame first appears to be reset, but then is reloaded and ends up in the second state.
This is because we have a callback that reloads the frame when there is any change on the `complete` attribute : 
https://github.com/hotwired/turbo/blob/e2e5782776e565e80358c5ecd34e05c3b3bcf28c/src/core/frames/frame_controller.js#L101-L105
The morphing …
> Morphing + complete frame issue : Stop reloading turbo frames when complete attribute changes

- src/tests/functional/autofocus_tests.js
Closes [#1154][]
Replace bespoke CSS selector-based assertions with Playwright's built-in [toBeFocused](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-focused) assertion.
Like other assertions, `toBeFocused` will wait and retry for a period of time, which makes `nextBeat` calls unnecessary.
[#1154]: https://github.com/hotwired/turbo/issues/1154
> Use Playwright assertions for autofocus

- src/core/streams/actions/morph.js
- src/core/streams/stream_actions.js
- src/tests/fixtures/morph_stream_action.html
- src/tests/functional/morph_stream_action_tests.js
- src/tests/unit/stream_element_tests.js
This PR introduces a morph Turbo Stream action. The motivation for this addition stems from the recent discussions and suggestions in issue [#1163](https://github.com/hotwired/turbo/issues/1163). There is a clear interest in providing users with more flexible options for DOM manipulation, especially for those not ready or looking to fully transition to using Turbo's full page morphing capabilities.
turbo-rails PR https://github.com/hotwired/turbo-rails/pull/583
documentation PR https://github.com/hotwired/turbo-site/pull/169
> Add Turbo stream morph action

- src/core/drive/page_view.js
- src/tests/fixtures/422_morph.html
- src/tests/fixtures/page_refresh.html
- src/tests/functional/autofocus_tests.js
- src/tests/server.mjs
While trying to port the Turbo Morph Demo over to Django, I found that if a form submission returns a classic django error page, the morph renderer is still used, causing an undesired blend of the previous pages <head> tags with the error page's content.  
Since morphing is predicated on the idea of a full-page refresh, the tag `<meta name="turbo-refresh-method" content="morph">` should be on all responses that intend to be morphed, and if not (as the case of an error page), it would be ideal to fallback on the full page renderer.  
This PR checks both the current page AND the upcoming snapshot for the meta setting `refresh-method='morph'` to determine if the morph renderer should be used, instead of just the originating page.
https://github.com/hotwired/turbo/assets/1790447/96d7ec6e-e791- …
> Check new snapshot (instead of previous) for refresh-method

- src/tests/functional/link_prefetch_observer_tests.js
The test aimed to verify that no network request occurs when clicking a link that had already been prefetched by hovering. However, instead of performing a click, the test erroneously attempted to hover over the link again, which had already been hovered over. Therefore, it failed to test the intended behavior.
This PR makes sure that the test is correctly set up to prevent any regression in this functionality.
> Fix test to verify no network request on prefetched link click

- src/core/drive/morph_renderer.js
- src/core/renderer.js
- src/tests/fixtures/autofocus.html
- src/tests/functional/autofocus_tests.js
- src/tests/functional/page_refresh_tests.js
Before this change, Turbo would always focus on the first element with `[autofocus]` when a page refresh with morphing happened  (default behavior inherited from `PageRenderer`). With this change, it will never autofocus when a page refresh with morphing happens.
This is meant to solve the problem where you are writing on a form, and it loses the focus because a broadcasted page refresh arrives.
> Don't lose focus due to autofocus when morphing pages

- src/core/drive/navigator.js
- src/core/session.js
- src/tests/fixtures/page_refresh.html
- src/tests/fixtures/test.js
- src/tests/functional/page_refresh_tests.js
- src/tests/helpers/page.js
Closes [#1209]
Defers the `Session.refresh` calls while handling `<turbo-stream action="refresh">` elements if there is a `Visit` that's already initiated and being handled by the `Navigator`.
[#1209]: https://github.com/hotwired/turbo/issues/1209
> Prevent Refresh from interrupting ongoing Visit

- src/core/frames/link_interceptor.js
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.js
The scenario
---
Imagine a List-Details style page layout, with navigation links on the left and the contents of the page on the right:
```html
<turbo-frame id="list">
<a href="/articles/1" data-turbo-frame="details">
Article #1
<turbo-frame id="preview_article_1" src="/articles/1/preview">
Some preview text
</turbo-frame>
</a>
<a href="/?page=2">Next Page</a>
</turbo-frame>
<turbo-frame id="details">
<h1>Details</h1>
</turbo-frame>
```
The `#list` element is a `<turbo-frame>` to handle pagination, and the `#details` element is a `<turbo-frame>` as well. The `<a>` elements within the `#list` frame drive the `#details` frame through their `[data-turbo-frame="details"]`. The `<a>` element nests a third kind of `<turbo-frame>` that is specific to the resource being linked to. It …
> Resolve Turbo Frame navigation bug

- src/elements/stream_element.js
The JSDoc comment for the `StreamElement` is incorrect, and omits several actions.
This commit sorts the list, replaces `"container"` with `"target"` (to mirror the attribute name), and mentions the missing actions.
> Update JSDoc for `StreamElement`

- src/http/fetch_request.js
- src/observers/link_prefetch_observer.js
- src/tests/functional/form_submission_tests.js
- src/tests/functional/visit_tests.js
Fixes #1100
In 7.3 this was always upper cased but in v8 it is not. This breaks forms that use formmethod on buttons. On chrome and firefox puma returns a 400 but once the method is uppercased it works.
https://github.com/hotwired/turbo/blob/4593d06ce58d17af5b17495ad8524eaa9bc2f5d2/src/http/fetch_request.ts#L143
> Ensure fetch method is always uppercase

- src/observers/form_submit_observer.js
- src/observers/link_click_observer.js
- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.js
- src/util.js
Closes [#1171][]
Forms that target [_blank][form-target-blank] along with anchors that target [_blank][] navigate new tabs, and are therefore incompatible with Turbo's long-lived session.
This commit ensures that both `<a>` and `<form>` submissions that target `_blank` are ignored.
[#1171]: https://github.com/hotwired/turbo/issues/1171
[form-target-blank]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#target
[anchor-target-blank]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#target
> Ignore links and forms that target `"_blank"`

- src/tests/fixtures/hover_to_prefetch.html
- src/tests/fixtures/test.js
- src/tests/functional/link_prefetch_observer_tests.js
Expand the link prefetching functional test coverage to exercise prefetching in relation to the events dispatched during the lifecycle. For example, include coverage for:
* `turbo:before-prefetch` being dispatched
* `turbo:before-prefetch` being canceled
* `turbo:before-fetch-request` dispatched only once during a successful prefetch
> Add `turbo:before-prefetch` test coverage

- src/core/config/drive.js
- src/core/config/forms.js
- src/core/config/index.js
- src/core/drive/form_submission.js
- src/core/index.js
- src/core/session.js
- src/tests/fixtures/drive_disabled.html
- src/tests/functional/form_submission_tests.js
- src/tests/unit/export_tests.js
- src/util.js
Depends on [#1217][]
===
Follow-up to [#386][]
While Turbo's support for disabling a Form Submissions `<input
type="submit">` or `<button>` element is rooted in [Rails UJS][], it
degrades (and has always degraded) the accessibility of those
experiences.
To learn more about the risks involved, read the [Don't Disable
Submits][] section of Adrian Roselli's [Don't Disable Form Controls][]
along with the additional resources mentioned therein.
The risk of degrading accessibility is especially true for Morph-enabled
Form Submissions. If a form submission will trigger a morphing Page
Refresh with the submitter focused, it's likely that the focus *is
intended to* remain on the submitter.
With the current `[disabled]` behavior, that is not possible without a
bespoke event handler like:
```js …
```
> Configure Submitter disabling

- src/core/config/drive.js
- src/core/config/forms.js
- src/core/config/index.js
- src/core/drive/form_submission.js
- src/core/index.js
- src/core/session.js
- src/tests/fixtures/drive_disabled.html
- src/tests/functional/form_submission_tests.js
- src/tests/unit/export_tests.js
The initial implementation aims to replace the ad hoc configurations spread across `window.Turbo` and `Turbo.session`. Those objects shouldn't be considered part of the public interface, especially for extension.
This commit exports a single object from `src/core/config` to serve as a centralized, user-facing repository for configuration values.
The main `src/core/config` object is composed of two constituent parts:
* `src/core/config/drive`
* `src/core/config/forms`
In the future, the directory structure can be expanded upon to suit the needs of the project.
Any user-facing configuration outside of `Turbo.config` is deprecated.
> Introduce `Turbo.config` object

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- package.json
- yarn.lock
I wanted to try some changes to turbo source on to get myself started quickly I tried using the devcontainer setup but it didn't work. So instead I spent the time debugging that issue.
The devcontainer was no longer working since chrome version 115 because location of installation files changed. See comment on: https://chromedriver.chromium.org/downloads
However we don't need to build it ourselves since Microsoft maintains docker images with playwright preinstalled with chrome, firefox and webkit.
This means that we can simplify the setup a lot while still keeping the goal of allowing people to get an environment in which they can run tests by simply starting a devcontainer or running a Github codespace.
I've just tested this now by launching a github codespace from this here branch on my …
> Fix devcontainer configuration

- src/core/drive/visit.js
- src/tests/fixtures/cache_observer.html
- src/tests/fixtures/visit.html
- src/tests/functional/visit_tests.js
> Fix temporary elements disappearing on subsequent GET requests that redirect to a page with data-turbo-temporary elements.

- src/core/drive/page_view.js
- src/core/frames/frame_controller.js
- src/core/frames/morphing_frame_renderer.js
- src/core/renderer.js
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.js
Follow-up to [#1192][]
Closes [#1303][]
Remove the argument from all `Renderer` subclass constructor call sites.
In its place, define the default value for the `Renderer.renderElement`
property based on the `static renderElement(currentElement, newElement)`
defined by the inheriting class.
By automatically determining which `renderElement` implementation based
on class, this commit enables a simpler Frame morphing strategy. Instead
of attaching one-time event listeners, this commit maintains a private
`#shouldMorphFrame` property that is set, then un-set during the
rendering lifecycle of a frame.
Similarly, this commit implements the
`MorphingFrameRenderer.preservingPermanentElements` method in the same
style as the `MorphingPageRenderer.preservingPermanentElements`. Since
_instances_ of …
> Infer `renderElement` during `Renderer` construction

- src/core/drive/progress_bar.js
- src/util.js
This PR allows Turbo to support https://github.com/rails/rails/pull/51729. This changes Turbo to read the meta tag's `nonce` attribute first and fall back to the `content` attribute.
As described in https://github.com/rails/rails/issues/51580#issue-2246912613 this makes it harder to extract the nonce value.
> Read the csp meta tag nonce attribute and fall back to content

- src/core/drive/visit.js
It's extracted to util file in #618 but the origin was left behind.
I'd like to run the test locally but playright doesn't play well with alpine so it's not tested 😬 The changes do look relatively straightforward though.
> Remove unused `getHistoryMethodForAction` function in Visit

- src/core/session.js
- src/tests/fixtures/page_refresh_stream_action.html
- src/tests/functional/page_refresh_stream_action_tests.js
There is a race condition with Turbo 8 refreshes and regular navigation through the application, caused by passing the URL to be refreshed into the debounced function.
If user visits another page, **in between** the page refresh arriving and the debounced refresh execution, the stale URL in the debounced refresh will navigate back to the page the user just came from.
This behavior is most apparent when there is a steady stream of turbo refreshes coming in and user is navigating through pages that receive these refreshes, but could happen at any (low) volume of page refreshes, if the timing is right.
Here's a video of the issue:
https://github.com/hotwired/turbo-rails/assets/32981/48f438a6-244f-4070-9439-44044c043d92
* At the end you can observe I click on "Show this item" of the item …
> Fix stale refresh URL caused by debouncing

- src/elements/stream_element.js
- src/tests/unit/stream_element_tests.js
Since form controls can be accessed in javascript directly by name through the form object, (e.g. `my_form.my_input`), `c.id` may end up referring to an _element_ whose name is `id`, instead of referring to the global id _attribute_. Explicitly retrieving the id with `getAttribute` avoids this.
Fixes #879
> Use getAttribute to find duplicate ids, not the id property

- src/core/drive/navigator.js
- src/core/native/browser_adapter.js
- src/core/session.js
- src/tests/unit/native_adapter_support_tests.js
This resolves an issue found in the Hotwire Native iOS library. See: https://github.com/hotwired/hotwire-native-ios/issues/12
Link prefetching is being triggered on link taps on iOS, which has unintended consequences in the Hotwire Native iOS library. This causes double `GET` requests when crossing the `default` and `modal` context session boundaries, which use separate `WKWebView` instances.
Additionally, some urls correspond to natively implemented screens, not webviews, so link prefetching is undesirable for these cases, too.
This change allows the Hotwire Native libraries to have control of the link prefetching behavior. We will disable link prefetching in the native libraries where link hovering is not available.
Here are the corresponding Hotwire Native iOS and Hotwire Native …
> Verify with the browser adapter before initiating link prefetching

- src/tests/fixtures/422.html
- src/tests/fixtures/422_morph.html
- src/tests/fixtures/422_tall.html
- src/tests/fixtures/form.html
- src/tests/fixtures/page_refresh.html
- src/tests/functional/form_submission_tests.js
- src/tests/functional/page_refresh_tests.js
This is an alternative to https://github.com/hotwired/turbo/pull/1277 which looks abandoned.
> rename unprocessable entity to unprocessable content to match Rack

- src/tests/functional/stream_tests.js
Resolves: https://github.com/hotwired/turbo/issues/1258
It's paired with: https://github.com/hotwired/turbo-site/pull/192
As a consequence of the fundamental way in which Stream actions are implemented, they can also be executed by rendering them within any HTML that's included on the dom.
Since this is already being used as the feature in the community, adding this test will ensure this keeps working.
> Add a test that stream actions rendered into the HTML are executed

- .github/workflows/ci.yml
All PRs are currently red because GitHub has intentionally broken `actions/upload-artifact@v3` to force an upgrade to v4.
From any recent CI run:
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Below are the breaking changes for v4, none of which seem to apply to Turbo, so a simple bump should do.
https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
> Bump actions/upload-artifact to v4 to get CI green again

- package.json
- src/core/morphing.js
- src/tests/fixtures/permanent_children.html
- src/tests/functional/page_refresh_tests.js
- yarn.lock
Hi folks, this is a redux of #1308 with an alternative strategy: fixing the issue in Idiomorph.
I'm building a collaborative issue tracking app, and one of the issue tracker app's primary use-cases has exposed a bug in the integration between Idiomorph and the `data-turbo-permanent` attribute. Each ticket contains a `data-turbo-permanent` checkbox to keep track of the client-side state of whether or not the ticket is currently expanded for that client or not. We also allow tickets to be reordered via drag-and-drop. The issue is that this `data-turbo-permanent` checkbox is not always preserved across morphs involving ticket reorders. There are other more serious ramifications of this bug (data loss!), but this is the simplest case to illustrate the issue.
I have reduced this scenario down …
> Fix bug where Idiomorph sometimes ignores data-turbo-permanent

- playwright.config.js
* Many tests assert that certain browser events occurred using a helper named `nextEventNamed`. To deal with asynchronicity, this helper waits until  the specified event occurs. If the event never occurs, it loops forever until the the default Playwright test timeout is reached.
* The default Playwright test timeout is 30 seconds.
* Playwright is configured to retry failing tests for a max of 3 total runs.
* Playwright is configured to run tests on both Chromium and Firefox.
When developing Turbo and running tests frequently, if even one of these event assertion fails, we're looking at a _minimum of 3 minutes_ before the test run completes! And that's the best-case scenario of running only one individual test... often we're running many, and if one test fails, often other tests are …
> Better testing timeouts for less painful development

- src/tests/functional/rendering_tests.js
- src/tests/helpers/page.js
Following up upon https://github.com/hotwired/turbo/pull/1317 , this time without adding a timeout parameter!
With this commit, I'm seeing the minimum wait for a failure result drop from 0:60 to 0:15 when one of these assertions is failing.
> Add 2 second timeouts to infinitely-looping assertions

- src/core/drive/morphing_page_renderer.js
- src/core/frames/morphing_frame_renderer.js
- src/core/morphing.js
- src/core/renderer.js
- src/tests/fixtures/frames.html
- src/tests/functional/frame_tests.js
Hi folks, here's what seems to me to be the next obvious step after #1192 changed `reload()` to morph a morphing frame.
Imagine the following page structure: a morphing page with a morphing frame that itself includes another morphing frame, i.e.
```
Morphing Page > Morphing Frame Child > Morphing Frame Grandchild
```
Refreshing `Morphing Page` already triggers morphing `reload()`s on both the `Morphing Frame Child` and on `Morphing Frame Grandchild`. However, manually triggering `reload()` on `Morphing Frame Child` does NOT trigger a `reload()` on `Morphing Frame Grandchild`, but rather does a full non-morphing render. This seems inconsistent and surprising.
Morphing pages now only trigger `reload()`s on their immediate morphing frame children, and then leaves it up to them to trigger …
> Reloading a morphing frame should trigger reloads on its child morphing frames recursively

- src/http/fetch.js
This reverts the change made in #1077 in order to restore compatibility with other JS libraries that depend on modifying `window.fetch`.
Related issue: #1371
(copied from #1371)
If another library is instantiated after Turbo and modifies `window.fetch`, `Turbo.fetch` ignores any modified behavior because Turbo still references the original `window.fetch` at the time of its own instantiation.
Concretely, this means that users have to write a hack in Rails applications to wait to import Turbo until everything else is imported and instantiated. For example, with Datadog RUM, this is the required workaround (without this revert):
```js
import { datadogRum } from "@datadog/browser-rum";
function importTurbo(counter = 0) {
if (datadogRum.getInternalContent() || counter > 100) { …
```
> Revert fetch to call window.fetch directly again

- src/core/drive/page_snapshot.js
- src/tests/functional/drive_view_transition_tests.js
Closes: https://github.com/hotwired/turbo/issues/1408
This PR checks wether the user has requested reduced motion via their OS/browser and disables view-transitions if that is the case, see: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
The way it is currently made it will assume [no-preference](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#no-preference) by default in case a browser does not support the media query, matchMedia, or does not have window available
> Respect prefers-reduced-motion

- src/core/native/browser_adapter.js
- src/tests/fixtures/link_redirect.html
- src/tests/fixtures/link_redirect_target.html
- src/tests/functional/page_refresh_tests.js
Fixes https://github.com/hotwired/turbo/issues/1391
With this change, we store the effective location (`visit.redirectedToLocation`)  in `visitRequestCompleted` when the fetch was redirected. This makes sure the redirect is not executed again in case of a forced reload (which might lead to problems, see #1391).
> Make sure full page reloads use the response URL after a redirect

- src/observers/link_prefetch_observer.js
- src/tests/functional/link_prefetch_observer_tests.js
Fixes https://github.com/hotwired/turbo/issues/1372
With this change, prefetch requests will be made with the fetch priority set to `low`. This makes sure, that regular requests (default `high`) will be prioritized by the browser. Otherwise - on slow connections or servers - pending prefetches may pile up and block other fetches until fully processed.
> Improve prefetch/navigation performance

- src/core/url.js
- src/tests/fixtures/root/index.html
- src/tests/fixtures/root/page.html
- src/tests/functional/root_test.js
- src/tests/functional/root_tests.js
Supersedes #1341, fixes #912
This is based on the work of @tobyzerner (#913), @leofeyer (#1341) and @packagethief (https://github.com/hotwired/turbo/pull/1341#issuecomment-3161810530) - I just added another test and made minor adjustments.
The original issue fixed by this PR, was Turbo not using Drive when navigating to the "turbo-root" itself.
> Fix navigating to the turbo-root does not use Turbo Drive

- src/tests/fixtures/navigation.html
- src/tests/functional/navigation_tests.js
- src/util.js
Currently, Turbo ignores any link with a target attribute set. However, this means that Turbo ignores the default `target="_self"`.
Some design systems and/or web components set the target to "_self" even though it's technically not required. Because they set this target, Turbo ignores a link it shouldn't be ignoring.
This commit ensures we're including the `target="_self"` on a link element when looking up a link from a click target.
The new Polaris web components are a good example of web components that explicitly set the `target="_self"` even though it's not needed according to the browser specs. 
- The browser specifications on the default target: https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#target
- Conversation with Shopify team: …
> Don't ignore the browser's default for `a[href]` links

- src/core/index.js
- src/core/morphing.js
- src/tests/unit/export_tests.js
Related to https://github.com/hotwired/turbo/issues/1177, https://github.com/hotwired/turbo/issues/1085
Document and export the range of morphing available to Turbo's internals. The continuum spans from morphing elements, to morphing their children, to morphing turbo-frame elements, to morphing body elements.
Instead of exporting Idiomorph directly, this commit exports a mix of the utility functions and the Morphing-prefixed `.renderElement` class functions. This way, the range of `turbo:`-prefixed are dispatched regardless of whether the call originated Turbo-side or application-side.
> Expose morphing functions for consumer use
